/**
 * Tarot Detailed Interpretations — Lời giải chi tiết cho 22 lá Ẩn Chính
 * và hướng dẫn theo chủ đề (Tình yêu, Sự nghiệp, Tài chính, Sức khỏe)
 */

export const MAJOR_DETAILS = {
  0: { love: 'Một mối tình đầy bất ngờ, tự phát và hồn nhiên đang chờ đón. Nếu đang trong mối quan hệ, hãy để sự tươi mới quay lại bằng những cuộc phiêu lưu cùng nhau.', career: 'Thời điểm lý tưởng để bắt đầu dự án mới hoặc thử sức ở lĩnh vực hoàn toàn mới. Đừng sợ rủi ro — sự ngây thơ của bạn lại chính là sức mạnh.', finance: 'Tài chính có thể bấp bênh do thiếu kế hoạch, nhưng đây cũng là lúc cơ hội bất ngờ xuất hiện. Hãy cẩn thận nhưng đừng quá sợ hãi.', health: 'Năng lượng tràn đầy và tinh thần phấn chấn. Hãy thử một môn thể thao mới hoặc thay đổi lối sống.' },
  1: { love: 'Bạn có sức hút mãnh liệt, quyến rũ người đối diện bằng sự tự tin. Nếu độc thân, đây là lúc chủ động tạo cơ hội gặp gỡ.', career: 'Mọi nguồn lực đều sẵn sàng — bạn chỉ cần hành động. Khả năng thuyết trình, đàm phán và sáng tạo đang ở đỉnh cao.', finance: 'Khả năng kiếm tiền tuyệt vời nhờ tài năng và sự khéo léo. Đầu tư vào bản thân sẽ sinh lời gấp nhiều lần.', health: 'Sức khỏe tốt, nhưng cần cân bằng giữa làm việc và nghỉ ngơi để tránh kiệt sức.' },
  2: { love: 'Một bí mật trong tình yêu sắp được hé lộ. Hãy tin vào trực giác — nó sẽ dẫn bạn đến câu trả lời đúng.', career: 'Đừng vội đưa ra quyết định lớn. Hãy quan sát, lắng nghe và để trực giác hướng dẫn. Kiến thức ẩn giấu sẽ sớm lộ diện.', finance: 'Có thể có những khoản chi tiêu ẩn hoặc thông tin tài chính chưa rõ ràng. Hãy kiểm tra kỹ trước khi ký kết.', health: 'Chú ý đến sức khỏe tinh thần và trực giác cơ thể. Thiền định và yoga rất có lợi trong giai đoạn này.' },
  3: { love: 'Tình yêu nồng ấm, phong phú và đầy sáng tạo. Nếu đang có mối quan hệ, đây là giai đoạn lãng mạn nhất. Khả năng mang thai hoặc sinh con cao.', career: 'Sáng tạo bùng nổ. Các dự án nghệ thuật, truyền thông hoặc liên quan đến cái đẹp sẽ thịnh vượng.', finance: 'Sự dồi dào tài chính. Thu nhập ổn định và có thể tăng thêm từ các ý tưởng sáng tạo.', health: 'Sức khỏe tuyệt vời. Hãy kết nối với thiên nhiên — đi dạo, làm vườn sẽ nạp năng lượng cho bạn.' },
  4: { love: 'Mối quan hệ cần sự ổn định và cam kết rõ ràng. Nếu bạn đang hẹn hò, đây là lúc nghiêm túc hơn hoặc thiết lập ranh giới.', career: 'Vị trí lãnh đạo hoặc sự thăng tiến trong hệ thống cấp bậc. Kỷ luật và tư duy chiến lược là chìa khóa.', finance: 'Tài chính vững chắc nhờ quản lý chặt chẽ. Tuy nhiên, đừng quá bảo thủ — đôi khi cần mạo hiểm có tính toán.', health: 'Cần tập thể dục đều đặn và có lịch trình nghiêm ngặt. Sức khỏe phản ánh độ kỷ luật của bạn.' },
  5: { love: 'Bạn có thể tìm thấy tình yêu qua các nhóm cộng đồng, tôn giáo hoặc tổ chức. Mối quan hệ cần nền tảng giá trị chung.', career: 'Một người thầy, cố vấn hoặc tổ chức uy tín sẽ mở ra cánh cửa mới. Hãy tuân theo quy trình đã được chứng minh.', finance: 'Đầu tư vào giáo dục hoặc các khóa đào tạo sẽ sinh lời lâu dài. An toàn tài chính qua con đường truyền thống.', health: 'Các phương pháp truyền thống như Đông y, thiền định mang lại hiệu quả tốt hơn các liệu pháp mới lạ.' },
  6: { love: 'Một lựa chọn quan trọng trong tình yêu: cam kết sâu hơn hoặc chia tay. Hãy lắng nghe cả trái tim và lý trí.', career: 'Đôi khi bạn phải chọn giữa hai con đường sự nghiệp. Hãy chọn con đường phù hợp với giá trị cốt lõi.', finance: 'Quyết định tài chính quan trọng — hợp đồng, đầu tư, hoặc mua bán lớn. Hãy cân nhắc kỹ trước khi ký.', health: 'Cân bằng cảm xúc ảnh hưởng trực tiếp đến thể chất. Stress từ các mối quan hệ cần được giải tỏa.' },
  7: { love: 'Tình yêu mãnh liệt và đầy quyết tâm. Nếu gặp trở ngại, sự kiên trì sẽ giúp bạn vượt qua tất cả.', career: 'Thành công rực rỡ nhờ sự tập trung và nỗ lực không ngừng. Bạn đang trên đường chinh phục đỉnh cao.', finance: 'Tài chính cải thiện nhờ sự quyết đoán. Nhưng hãy cẩn thận với việc chi tiêu do adrenaline chiến thắng.', health: 'Năng lượng dồi dào nhưng cần kiểm soát căng thẳng. Đừng đẩy cơ thể quá giới hạn.' },
  8: { love: 'Kiên nhẫn và dịu dàng sẽ vượt qua mọi thử thách trong tình yêu. Đừng dùng sức mạnh — hãy dùng trái tim.', career: 'Thành công đến từ nội lực và sự bền bỉ, không phải bạo lực hay áp đặt. Hãy dẫn dắt bằng gương mẫu.', finance: 'Tài chính ổn định nhờ sự kiên nhẫn và kỷ luật. Không nên mạo hiểm lớn trong giai đoạn này.', health: 'Sức mạnh tinh thần giúp vượt qua bệnh tật. Các liệu pháp kết hợp tâm-thân rất hiệu quả.' },
  9: { love: 'Giai đoạn cần không gian cá nhân. Nếu đang trong mối quan hệ, hãy tôn trọng quyền riêng tư của đối phương.', career: 'Nghiên cứu, học tập sâu và làm việc độc lập mang lại kết quả tốt nhất. Tránh cộng tác quá nhiều.', finance: 'Thời điểm tốt để xem xét lại chiến lược tài chính của bạn. Tìm kiếm lời khuyên từ chuyên gia.', health: 'Cần thời gian nghỉ ngơi và tĩnh lặng. Thiền, đi bộ trong thiên nhiên giúp phục hồi tinh thần.' },
  10: { love: 'Số phận đang sắp đặt một cuộc gặp gỡ định mệnh. Hoặc mối quan hệ hiện tại sắp bước vào giai đoạn mới.', career: 'Thay đổi lớn trong sự nghiệp — thăng tiến, chuyển việc, hoặc cơ hội bất ngờ. Hãy sẵn sàng thích nghi.', finance: 'Vận may tài chính đang quay về phía bạn. Đây là lúc nắm bắt cơ hội đầu tư hoặc kinh doanh.', health: 'Sức khỏe biến động theo chu kỳ. Nếu đang khỏe, hãy duy trì. Nếu đang yếu, chu kỳ phục hồi đang bắt đầu.' },
  11: { love: 'Sự thật trong tình yêu sẽ được phơi bày. Mối quan hệ cần sự trung thực tuyệt đối để phát triển.', career: 'Công bằng sẽ chiến thắng trong công việc. Nếu bạn làm đúng, kết quả xứng đáng sẽ đến.', finance: 'Các vấn đề pháp lý, hợp đồng hoặc tranh chấp tài chính sẽ được giải quyết công bằng.', health: 'Cân bằng là chìa khóa. Kiểm tra sức khỏe định kỳ và lắng nghe cơ thể.' },
  12: { love: 'Hãy nhìn mối quan hệ từ góc nhìn khác. Sự hy sinh đôi khi cần thiết cho tình yêu trưởng thành.', career: 'Tạm dừng dự án hiện tại không phải là thất bại — đó là sự sáng suốt. Góc nhìn mới sẽ dẫn đến đột phá.', finance: 'Đây không phải thời điểm đầu tư mạo hiểm. Hãy giữ tiền và chờ đợi cơ hội tốt hơn.', health: 'Cơ thể đang yêu cầu nghỉ ngơi. Yoga, thiền định và các hoạt động chậm rãi rất phù hợp.' },
  13: { love: 'Một giai đoạn kết thúc: có thể là chia tay, nhưng cũng có thể là sự chuyển hóa sâu sắc trong mối quan hệ hiện tại.', career: 'Dự án cũ kết thúc, vị trí cũ thay đổi — nhưng từ đống tro tàn sẽ nảy sinh cơ hội mới tuyệt vời.', finance: 'Xóa sổ nợ cũ hoặc thay đổi hoàn toàn nguồn thu nhập. Kết thúc để bắt đầu lại.', health: 'Thay đổi lối sống triệt để sẽ mang lại kết quả tuyệt vời. Bỏ thói quen xấu ngay bây giờ.' },
  14: { love: 'Cân bằng trong mối quan hệ là chìa khóa. Không quá nồng nhiệt cũng không quá lạnh nhạt — hãy tìm điểm giữa.', career: 'Kiên nhẫn và hợp tác mang lại thành công. Đừng vội vàng — mọi thứ cần thời gian để chín muồi.', finance: 'Quản lý tài chính cần điều độ. Không tiết kiệm quá mức cũng không tiêu xài hoang phí.', health: 'Cần cân bằng dinh dưỡng, giấc ngủ và tập luyện. Tránh mọi thứ thái quá.' },
  15: { love: 'Cẩn thận với mối quan hệ độc hại, ám ảnh hoặc phụ thuộc cảm xúc. Đam mê không nên biến thành xiềng xích.', career: 'Bạn có thể đang bị trói buộc bởi công việc không phù hợp. Nhận thức là bước đầu để giải thoát.', finance: 'Nghiện mua sắm, cờ bạc hoặc chi tiêu không kiểm soát. Hãy đối mặt với sự thật tài chính.', health: 'Chú ý đến các thói quen gây nghiện: đồ uống có cồn, caffeine, đường. Giải độc cơ thể và tâm trí.' },
  16: { love: 'Sự thật bất ngờ lay chuyển mối quan hệ. Đau đớn nhưng cần thiết để xây dựng lại nền tảng vững chắc hơn.', career: 'Biến cố lớn: mất việc, công ty tái cấu trúc, hoặc dự án sụp đổ. Nhưng đây là cơ hội để bắt đầu lại từ đầu.', finance: 'Tổn thất tài chính bất ngờ. Hãy chuẩn bị quỹ khẩn cấp và không đặt tất cả trứng vào một rổ.', health: 'Sức khỏe biến động đột ngột. Hãy đi khám ngay nếu có triệu chứng bất thường.' },
  17: { love: 'Hy vọng được đổi mới trong tình yêu. Nếu vừa trải qua đau khổ, ánh sáng đang dần trở lại.', career: 'Cảm hứng sáng tạo dồi dào. Đây là thời điểm tuyệt vời để theo đuổi ước mơ và dự án đam mê.', finance: 'Tài chính dần phục hồi sau giai đoạn khó khăn. Hãy kiên nhẫn và tin vào quá trình.', health: 'Sức khỏe cải thiện đáng kể. Năng lượng tích cực tràn ngập và tinh thần sáng lạn.' },
  18: { love: 'Sự nghi ngờ và hiểu lầm có thể gây rạn nứt. Hãy giao tiếp rõ ràng và đừng để nỗi sợ chi phối.', career: 'Không phải tất cả đều như vẻ bề ngoài tại nơi làm việc. Hãy cẩn thận với tin đồn và thông tin sai lệch.', finance: 'Có thể bị lừa đảo hoặc đầu tư sai. Hãy kiểm tra kỹ mọi thông tin tài chính trước khi hành động.', health: 'Lo âu và mất ngủ. Trực giác cơ thể rất quan trọng — hãy lắng nghe những tín hiệu ngầm.' },
  19: { love: 'Tình yêu rực rỡ, niềm vui tràn ngập. Mối quan hệ đang ở giai đoạn hạnh phúc nhất và tràn đầy năng lượng tích cực.', career: 'Thành công vang dội! Đây là thời điểm tỏa sáng, được công nhận và đạt đỉnh cao sự nghiệp.', finance: 'Tài chính thịnh vượng, thu nhập tăng và các khoản đầu tư sinh lời tốt.', health: 'Sức khỏe tuyệt vời, năng lượng dồi dào. Hãy tận hưởng cảm giác sống trọn vẹn.' },
  20: { love: 'Khoảnh khắc suy ngẫm sâu sắc về mối quan hệ. Tha thứ cho quá khứ và tái sinh tình yêu trên nền tảng mới.', career: 'Nhìn lại hành trình sự nghiệp và đánh giá lại mục đích. Tiếng gọi nội tâm dẫn bạn đến sứ mệnh thực sự.', finance: 'Thanh toán nợ cũ, kết thúc các khoản đầu tư không hiệu quả. Bắt đầu lại với chiến lược mới.', health: 'Phục hồi mạnh mẽ từ bệnh tật hoặc giai đoạn suy yếu. Cơ thể đang tái sinh.' },
  21: { love: 'Sự hoàn thành tuyệt đẹp — hôn nhân, cam kết lớn, hoặc cảm giác trọn vẹn trong tình yêu.', career: 'Hoàn thành dự án lớn, đạt mục tiêu sự nghiệp hoặc nhận được phần thưởng xứng đáng.', finance: 'Ổn định tài chính và cảm giác đầy đủ. Chu kỳ tích lũy đến đỉnh — hãy ăn mừng.', health: 'Sức khỏe toàn diện và hài hòa. Cơ thể, tâm trí và tình cảm đều ở trạng thái cân bằng.' },
};

// Lời giải mở rộng cho 4 bộ Minor Arcana (theo Suit)
export const SUIT_THEMES = {
  wands: { element: '🔥 Lửa', theme: 'Hành động, Đam mê, Sáng tạo', description: 'Bộ Gậy đại diện cho ngọn lửa bên trong — đam mê, tham vọng và sức mạnh hành động. Khi nhiều lá Gậy xuất hiện, cuộc sống của bạn đang ở giai đoạn năng động, sáng tạo và đầy nhiệt huyết.' },
  cups: { element: '💧 Nước', theme: 'Cảm xúc, Tình yêu, Trực giác', description: 'Bộ Cốc nói về dòng chảy cảm xúc — tình yêu, mối quan hệ và trực giác. Nhiều lá Cốc cho thấy các vấn đề cảm xúc đang chiếm vị trí trung tâm trong cuộc sống.' },
  swords: { element: '💨 Khí', theme: 'Trí tuệ, Xung đột, Sự thật', description: 'Bộ Kiếm đại diện cho lưỡi kiếm tư duy — sự minh mẫn, xung đột trí tuệ và sự thật đau đớn. Nhiều lá Kiếm cho thấy các quyết định khó khăn và thử thách tinh thần đang diễn ra.' },
  pentacles: { element: '🪙 Đất', theme: 'Vật chất, Tài chính, Công việc', description: 'Bộ Tiền kết nối với thế giới vật chất — tiền bạc, sự nghiệp và sức khỏe. Nhiều lá Tiền cho thấy các vấn đề thực tế, tài chính và an ninh đang cần chú ý.' },
};

export const getDetailForMajor = (id) => MAJOR_DETAILS[id] || null;
