/**
 * AstroBunny — Bộ bài Tarot hoàn chỉnh 78 lá (Tiếng Việt)
 * 22 Ẩn Chính (Major Arcana) + 56 Ẩn Phụ (Minor Arcana)
 */

const majorArcana = [
  { id: 0, name: 'Kẻ Ngốc', arcana: 'major', keywords: ['khởi đầu mới', 'ngây thơ', 'tự do', 'phiêu lưu'], uprightMeaning: 'Một khởi đầu mới đang chờ đón bạn. Hãy ôm lấy điều chưa biết với sự hồn nhiên và dũng cảm bước nhảy — vũ trụ đang ủng hộ hành trình của bạn.', reversedMeaning: 'Sự liều lĩnh hoặc nỗi sợ hãi trước điều chưa biết đang kìm hãm bạn. Hãy dừng lại và xem xét liệu bạn đang bốc đồng hay quá thận trọng.' },
  { id: 1, name: 'Nhà Ảo Thuật', arcana: 'major', keywords: ['hiện thực hóa', 'tài năng', 'sức mạnh ý chí', 'hành động'], uprightMeaning: 'Bạn đã có đủ mọi công cụ và tài năng cần thiết. Hãy tập trung ý chí để biến ước mơ thành hiện thực.', reversedMeaning: 'Tiềm năng chưa được khai phá hoặc sự lừa dối. Hãy cẩn thận với những mánh khóe — dù là từ chính bạn hay từ người khác.' },
  { id: 2, name: 'Nữ Tư Tế', arcana: 'major', keywords: ['trực giác', 'bí ẩn', 'tri thức nội tâm', 'tiềm thức'], uprightMeaning: 'Hãy tin vào trực giác và nhìn sâu hơn bề mặt. Câu trả lời nằm bên trong bạn — hãy lắng nghe tiếng nói nội tâm.', reversedMeaning: 'Bạn có thể đang phớt lờ trực giác hoặc giấu kín bí mật. Hãy kết nối lại với trí tuệ bên trong và để sự thật được phơi bày.' },
  { id: 3, name: 'Hoàng Hậu', arcana: 'major', keywords: ['sung túc', 'nuôi dưỡng', 'thiên nhiên', 'sáng tạo'], uprightMeaning: 'Giai đoạn phát triển và dồi dào bao quanh bạn. Hãy chăm sóc các dự án và mối quan hệ — chúng sẽ nở rộ tuyệt đẹp.', reversedMeaning: 'Bế tắc sáng tạo hoặc phụ thuộc quá mức vào người khác. Hãy khôi phục sự cân bằng giữa cho đi và nhận lại.' },
  { id: 4, name: 'Hoàng Đế', arcana: 'major', keywords: ['quyền lực', 'kỷ luật', 'ổn định', 'lãnh đạo'], uprightMeaning: 'Hãy nắm quyền với sự tự tin và thiết lập trật tự. Kỷ luật và tư duy chiến lược sẽ tạo nền tảng vững chắc cho bạn.', reversedMeaning: 'Sự cứng nhắc hoặc độc đoán. Kiểm soát quá mức kìm hãm sự phát triển — hãy nới lỏng và xem xét liệu quyền lực đã trở thành bạo quyền.' },
  { id: 5, name: 'Giáo Hoàng', arcana: 'major', keywords: ['truyền thống', 'tri thức tâm linh', 'dẫn dắt', 'niềm tin'], uprightMeaning: 'Hãy tìm kiếm sự hướng dẫn từ trí tuệ và truyền thống đã được thiết lập. Một người thầy có thể mang đến kiến thức bạn cần lúc này.', reversedMeaning: 'Đặt câu hỏi về quy ước và tự tìm con đường riêng. Hãy thoát khỏi những niềm tin cứng nhắc không còn phục vụ sự phát triển của bạn.' },
  { id: 6, name: 'Đôi Tình Nhân', arcana: 'major', keywords: ['tình yêu', 'hòa hợp', 'lựa chọn', 'kết nối'], uprightMeaning: 'Một mối liên kết ý nghĩa hoặc lựa chọn quan trọng đang ở trước mặt. Hãy theo trái tim nhưng vẫn trung thành với giá trị sâu xa nhất.', reversedMeaning: 'Bất hòa, lệch giá trị, hoặc né tránh lựa chọn khó khăn. Hãy suy ngẫm điều gì thực sự quan trọng trước khi cam kết.' },
  { id: 7, name: 'Cỗ Xe Chiến', arcana: 'major', keywords: ['quyết tâm', 'ý chí', 'chiến thắng', 'kiểm soát'], uprightMeaning: 'Chiến thắng nhờ quyết tâm sắt đá. Hãy kết hợp các lực lượng đối lập, tập trung vào mục tiêu và tiến lên với sự tự tin.', reversedMeaning: 'Thiếu định hướng hoặc hung hăng không mục đích. Bạn có thể đang ép buộc kết quả — hãy lùi lại và điều chỉnh hướng đi.' },
  { id: 8, name: 'Sức Mạnh', arcana: 'major', keywords: ['dũng cảm', 'kiên nhẫn', 'nội lực', 'từ bi'], uprightMeaning: 'Sức mạnh thực sự đến từ bên trong. Hãy đối mặt thử thách với lòng dũng cảm nhẹ nhàng và sự kiên định — sức mạnh mềm chiến thắng bạo lực.', reversedMeaning: 'Tự nghi ngờ hoặc yếu đuối nội tâm. Bạn có thể cảm thấy bất lực, nhưng sức mạnh bạn cần đã có sẵn bên trong — hãy kết nối lại.' },
  { id: 9, name: 'Ẩn Sĩ', arcana: 'major', keywords: ['tìm kiếm nội tâm', 'suy ngẫm', 'cô độc', 'trí tuệ'], uprightMeaning: 'Hãy rút lui khỏi sự ồn ào và tìm câu trả lời bên trong. Đây là thời điểm để suy ngẫm sâu sắc và tìm ánh sáng nội tâm.', reversedMeaning: 'Cô lập quá mức hoặc từ chối nhìn vào bên trong. Hãy cân bằng giữa cô đơn và kết nối — đừng để sự rút lui thành cô độc.' },
  { id: 10, name: 'Vòng Quay Vận Mệnh', arcana: 'major', keywords: ['thay đổi', 'chu kỳ', 'số phận', 'bước ngoặt'], uprightMeaning: 'Vòng quay đang xoay có lợi cho bạn. Hãy đón nhận thay đổi và nhận ra rằng cuộc sống vận hành theo chu kỳ — đây là khoảnh khắc chuyển biến tích cực.', reversedMeaning: 'Kháng cự sự thay đổi không thể tránh hoặc giai đoạn xui xẻo. Hãy nhớ rằng chu kỳ xấu rồi sẽ qua — hãy kiên cường và thích nghi.' },
  { id: 11, name: 'Công Lý', arcana: 'major', keywords: ['sự thật', 'công bằng', 'nhân quả', 'trách nhiệm'], uprightMeaning: 'Sự thật và công bằng sẽ chiến thắng. Hành động của bạn có hậu quả — hãy đưa ra quyết định với sự chính trực và tin rằng công lý sẽ được thực thi.', reversedMeaning: 'Thiếu trung thực hoặc trốn tránh trách nhiệm. Kết quả không công bằng có thể xuất phát từ tư duy thiên lệch. Hãy tìm kiếm sự thật.' },
  { id: 12, name: 'Người Treo Ngược', arcana: 'major', keywords: ['buông bỏ', 'góc nhìn mới', 'hy sinh', 'tạm dừng'], uprightMeaning: 'Hãy buông bỏ sự kiểm soát và nhìn thế giới từ một góc khác. Sự tạm dừng tự nguyện này mang lại hiểu biết sâu sắc và trưởng thành tâm linh.', reversedMeaning: 'Trì hoãn, do dự, hoặc hy sinh không cần thiết. Bạn có thể đang kháng cự sự thay đổi cần thiết — hãy ngừng trì hoãn và hành động.' },
  { id: 13, name: 'Tử Thần', arcana: 'major', keywords: ['chuyển hóa', 'kết thúc', 'tái sinh', 'thay đổi'], uprightMeaning: 'Một sự chuyển hóa mạnh mẽ đang diễn ra. Hãy buông bỏ điều không còn phục vụ bạn — kết thúc mở ra không gian cho những khởi đầu tươi đẹp.', reversedMeaning: 'Kháng cự sự thay đổi cần thiết hoặc sợ buông bỏ. Bám víu vào quá khứ ngăn cản sự tái sinh đang chờ đợi phía bên kia.' },
  { id: 14, name: 'Tiết Chế', arcana: 'major', keywords: ['cân bằng', 'điều độ', 'kiên nhẫn', 'hòa hợp'], uprightMeaning: 'Hãy tìm con đường trung dung và thực hành kiên nhẫn. Pha trộn các lực lượng đối lập thành sự hòa hợp — điều độ và bình tĩnh sẽ dẫn bạn đến mục tiêu.', reversedMeaning: 'Mất cân bằng, thái quá, hoặc thiếu tầm nhìn dài hạn. Hãy sắp xếp lại ưu tiên và khôi phục sự cân bằng trước khi tiến lên.' },
  { id: 15, name: 'Ác Quỷ', arcana: 'major', keywords: ['ràng buộc', 'vật chất', 'bóng tối', 'cám dỗ'], uprightMeaning: 'Hãy xem xét điều gì đang trói buộc bạn — nghiện ngập, thói quen độc hại, hay nỗi ám ảnh vật chất. Nhận thức là bước đầu tiên để giải thoát.', reversedMeaning: 'Giải phóng khỏi xiềng xích. Bạn đang giành lại sức mạnh và buông bỏ những ràng buộc không lành mạnh. Tự do đang trong tầm tay.' },
  { id: 16, name: 'Tháp Sụp Đổ', arcana: 'major', keywords: ['biến động', 'sụp đổ', 'thức tỉnh', 'giải phóng'], uprightMeaning: 'Một biến động bất ngờ lay chuyển nền tảng của bạn. Dù gây sốc, sự phá hủy này dọn đường để xây dựng lại trên nền tảng vững chắc hơn.', reversedMeaning: 'Tránh né thảm họa hoặc kháng cự sự sụp đổ không thể tránh. Trì hoãn khoảnh khắc sụp đổ chỉ kéo dài nỗi đau — hãy đón nhận sự đột phá.' },
  { id: 17, name: 'Ngôi Sao', arcana: 'major', keywords: ['hy vọng', 'niềm tin', 'đổi mới', 'cảm hứng'], uprightMeaning: 'Sau cơn bão đến ngôi sao. Hy vọng được đổi mới, cảm hứng và sự thanh thản tràn ngập tâm hồn bạn. Hãy tin rằng bạn đang đi đúng đường.', reversedMeaning: 'Mất niềm tin hoặc mất kết nối với hy vọng. Bạn có thể cảm thấy thiếu cảm hứng — hãy tìm những nguồn ánh sáng nhỏ để thắp lại tinh thần.' },
  { id: 18, name: 'Mặt Trăng', arcana: 'major', keywords: ['ảo ảnh', 'nỗi sợ', 'tiềm thức', 'trực giác'], uprightMeaning: 'Không phải mọi thứ đều như vẻ bề ngoài. Hãy vượt qua ảo tưởng và nỗi sợ bằng cách tin vào trực giác — tiềm thức chứa đựng thông điệp quan trọng.', reversedMeaning: 'Sự rõ ràng đang dần xuất hiện từ sự bối rối. Nỗi sợ đang được giải phóng và sự thật đang dần lộ ra. Hãy tin vào quá trình.' },
  { id: 19, name: 'Mặt Trời', arcana: 'major', keywords: ['niềm vui', 'thành công', 'sức sống', 'tích cực'], uprightMeaning: 'Niềm vui rạng rỡ và thành công tỏa sáng trên bạn. Đây là thời điểm của sự rõ ràng, ấm áp và lễ hội — hãy mở rộng vòng tay đón cuộc sống.', reversedMeaning: 'Giai đoạn tạm thời thiếu vui vẻ hoặc lạc quan bị che mờ. Mặt trời vẫn chiếu sáng sau những đám mây — đừng đánh mất điều tốt đẹp.' },
  { id: 20, name: 'Phán Xét', arcana: 'major', keywords: ['tái sinh', 'suy ngẫm', 'phán quyết', 'tiếng gọi nội tâm'], uprightMeaning: 'Khoảnh khắc phán quyết và tái sinh. Hãy suy ngẫm về hành trình, lắng nghe tiếng gọi nội tâm và vươn lên để đáp ứng mục đích cao hơn.', reversedMeaning: 'Tự nghi ngờ hoặc từ chối rút kinh nghiệm từ quá khứ. Sự phán xét khắc nghiệt với bản thân cản trở sự phát triển — hãy tha thứ cho chính mình.' },
  { id: 21, name: 'Thế Giới', arcana: 'major', keywords: ['hoàn thành', 'thành tựu', 'trọn vẹn', 'viên mãn'], uprightMeaning: 'Một chu kỳ đến hồi kết tuyệt đẹp. Bạn đã đạt được sự trọn vẹn và hòa hợp — hãy ăn mừng cột mốc này trước khi hành trình tiếp theo bắt đầu.', reversedMeaning: 'Mục tiêu chưa hoàn thành hoặc đi đường tắt. Có điều gì đó còn dang dở — hãy hoàn tất trước khi vội vã bước vào chương tiếp theo.' },
];

const wands = [
  { id: 22, name: 'Át Gậy', arcana: 'minor', suit: 'wands', keywords: ['cảm hứng', 'cơ hội mới', 'tia sáng sáng tạo'], uprightMeaning: 'Một năng lượng sáng tạo bùng nổ đang khởi động dự án mới trong cuộc đời bạn. Lá bài này báo hiệu thời điểm chín muồi để gieo hạt giống cho những ý tưởng lớn. Hãy nắm bắt cơ hội với đam mê cháy bỏng và để nhiệt huyết nội tâm dẫn đường. Vũ trụ đang trao cho bạn ngọn lửa khởi đầu — hãy sử dụng nó một cách khôn ngoan trước khi nó tắt.', reversedMeaning: 'Sự trì hoãn đang làm tắt ngọn lửa sáng tạo bên trong bạn. Tia lửa cảm hứng vẫn đang cháy nhưng bị chặn bởi nỗi sợ thất bại hoặc thiếu tự tin. Có thể bạn đang chờ đợi "thời điểm hoàn hảo" mà quên rằng thời điểm tốt nhất là ngay bây giờ. Hãy dọn dẹp những chướng ngại tinh thần và kết nối lại với đam mê ban đầu của mình.' },
  { id: 23, name: 'Hai Gậy', arcana: 'minor', suit: 'wands', keywords: ['lên kế hoạch', 'quyết định', 'khám phá'], uprightMeaning: 'Bạn đang đứng ở ngã rẽ quan trọng với cả thế giới rộng mở trong tầm tay. Đây là lúc nhìn ra xa hơn vùng an toàn quen thuộc và lên kế hoạch cho những bước tiến táo bạo. Một quyết định lớn đang chờ bạn — và dù chọn hướng nào, điều quan trọng là bạn dám bước đi. Hãy tin vào tầm nhìn của mình, vì thế giới đang rộng mở chào đón bạn.', reversedMeaning: 'Nỗi sợ trước điều chưa biết đang giam giữ bạn trong vùng an toàn nhỏ bé. Bạn có thể đang trì hoãn quyết định quan trọng vì lo lắng về hậu quả, nhưng sự không hành động cũng là một lựa chọn — và thường là lựa chọn tệ nhất. Thiếu kế hoạch dài hạn khiến bạn bỏ lỡ những cơ hội quý giá đang qua.' },
  { id: 24, name: 'Ba Gậy', arcana: 'minor', suit: 'wands', keywords: ['mở rộng', 'tầm nhìn xa', 'tiến triển'], uprightMeaning: 'Kế hoạch của bạn đang dần thành hình rõ nét và sự mở rộng đang diễn ra mạnh mẽ. Giống như con thuyền ra khơi, bạn đang nhìn về phía chân trời với niềm tin vững chắc rằng mình sẽ đến nơi. Đây là thời điểm để tận dụng đà tiến và mở rộng tầm ảnh hưởng. Sự hợp tác quốc tế hoặc mở rộng sang lĩnh vực mới rất thuận lợi.', reversedMeaning: 'Những trở ngại bất ngờ đang làm chậm tiến độ và khiến bạn nản lòng. Sự thất vọng với kết quả đến chậm hơn mong đợi có thể khiến bạn muốn bỏ cuộc. Tuy nhiên, đây chỉ là sự chậm trễ tạm thời, không phải thất bại. Hãy đánh giá lại chiến lược, điều chỉnh kế hoạch và kiên nhẫn — mùa thu hoạch sẽ đến.' },
  { id: 25, name: 'Bốn Gậy', arcana: 'minor', suit: 'wands', keywords: ['lễ hội', 'đoàn tụ', 'hòa hợp'], uprightMeaning: 'Đây là thời điểm ăn mừng, vui vẻ và tận hưởng những thành quả đã đạt được. Các cột mốc quan trọng đã hoàn thành và cộng đồng tụ họp trong sự hòa hợp đầy ấm áp. Giống như một lễ hội thu hoạch, bạn được bao quanh bởi tình yêu thương và sự ủng hộ. Hãy trân trọng khoảnh khắc này và chia sẻ niềm vui với những người xung quanh.', reversedMeaning: 'Bạn có thể cảm thấy không được chào đón hoặc bị loại trừ khỏi một nhóm nào đó. Lễ hội xung quanh có vẻ trống rỗng và giả tạo, hoặc bạn đang tự cô lập mình khỏi niềm vui. Những căng thẳng ngầm trong các mối quan hệ cần được giải quyết trước khi chúng phá hỏng không khí. Hãy tìm cách kết nối lại với cộng đồng và mở lòng đón nhận sự ấm áp.' },
  { id: 26, name: 'Năm Gậy', arcana: 'minor', suit: 'wands', keywords: ['xung đột', 'cạnh tranh', 'căng thẳng'], uprightMeaning: 'Sự cạnh tranh lành mạnh đang thúc đẩy bạn phát triển và vượt qua giới hạn bản thân. Năm chiếc gậy va chạm tượng trưng cho những cuộc tranh luận sôi nổi, sự ganh đua trong công việc hoặc xung đột ý kiến. Tuy nhiên, đây không phải là xung đột hủy diệt — mà là ngọn lửa rèn luyện. Hãy đón nhận thử thách với tinh thần thể thao và để xung đột trở thành chất xúc tác cho sự cải thiện.', reversedMeaning: 'Bạn đang né tránh xung đột cần thiết hoặc chịu đựng sự bất ổn nội tâm khó chịu. Những căng thẳng bị kìm nén đang âm thầm tích tụ và có thể bùng nổ bất cứ lúc nào. Sự cạnh tranh có thể đã trở thành thù địch, hoặc bạn đang mệt mỏi với những cuộc tranh chấp vô nghĩa. Hãy giải quyết mâu thuẫn trước khi chúng leo thang vượt tầm kiểm soát.' },
  { id: 27, name: 'Sáu Gậy', arcana: 'minor', suit: 'wands', keywords: ['chiến thắng', 'công nhận', 'thành công'], uprightMeaning: 'Đây là khoảnh khắc chiến thắng vinh quang — nỗ lực không ngừng nghỉ của bạn cuối cùng đã được công nhận. Giống như vị tướng khải hoàn trở về, bạn nhận được sự ngưỡng mộ và tôn trọng từ mọi người. Danh tiếng và uy tín đang ở đỉnh cao, và bạn xứng đáng tận hưởng thành công này. Hãy đón nhận vinh quang với sự khiêm tốn, và nhớ cảm ơn những người đã đồng hành.', reversedMeaning: 'Nỗ lực của bạn chưa được ghi nhận xứng đáng hoặc bạn đang tự tạo ra vẻ thành công giả tạo. Có thể ai đó đang nhận công lao thuộc về bạn, hoặc bạn đang tự lừa dối mình về mức độ thành tựu thực sự. Sự thiếu công nhận gây thất vọng sâu sắc, nhưng hãy nhớ rằng giá trị thực không phụ thuộc vào lời khen của người khác.' },
  { id: 28, name: 'Bảy Gậy', arcana: 'minor', suit: 'wands', keywords: ['kiên trì', 'phòng thủ', 'giữ vững'], uprightMeaning: 'Bạn đang đứng vững trước nhiều thách thức đến từ mọi phía, nhưng vị thế của bạn rất mạnh mẽ. Giống như người chiến binh một mình chống lại sáu đối thủ từ vị trí cao, bạn có lợi thế chiến lược dù bị áp đảo về số lượng. Lòng dũng cảm và niềm tin sẽ giúp bạn vượt qua giai đoạn khó khăn này. Hãy bảo vệ những gì bạn tin tưởng và đừng bao giờ lùi bước.', reversedMeaning: 'Cảm giác choáng ngợp trước quá nhiều vấn đề cùng lúc đang khiến bạn muốn bỏ cuộc. Bạn có thể đang chiến đấu những trận chiến không đáng để tiêu hao năng lượng, hoặc đang cố gắng bảo vệ điều đã không còn giá trị. Đôi khi, sự khôn ngoan nằm ở việc biết khi nào nên rút lui chiến thuật để bảo toàn lực lượng cho những trận chiến quan trọng hơn.' },
  { id: 29, name: 'Tám Gậy', arcana: 'minor', suit: 'wands', keywords: ['hành động nhanh', 'chuyển động', 'đà tiến'], uprightMeaning: 'Mọi thứ đang chuyển động với tốc độ chóng mặt và bạn cần bắt kịp nhịp độ này. Tin tức quan trọng, sự kiện bất ngờ hoặc cơ hội nhanh chóng đang lao đến như tám mũi tên xuyên không. Đà tiến rất mạnh mẽ và thuận lợi — hãy tận dụng năng lượng này để đẩy nhanh các dự án. Du lịch, di chuyển hoặc thay đổi môi trường cũng rất được ưu ái trong giai đoạn này.', reversedMeaning: 'Sự chậm trễ đáng bực bội đang cản trở tiến độ kế hoạch của bạn. Mọi thứ dường như bị đình trệ dù bạn đã cố gắng hết sức — email không được trả lời, cuộc hẹn bị hủy, dự án bị hoãn. Hoặc ngược lại, mọi thứ đang diễn ra quá nhanh khiến bạn không kịp xử lý và quyết định vội vàng. Hãy chậm lại, hít thở và đảm bảo bạn vẫn đang đi đúng hướng.' },
  { id: 30, name: 'Chín Gậy', arcana: 'minor', suit: 'wands', keywords: ['bền bỉ', 'kiên cường', 'trận chiến cuối'], uprightMeaning: 'Bạn đã trải qua rất nhiều thử thách và giờ đây đang ở gần đích cuối cùng. Dù mệt mỏi và đầy vết thương, sự bền bỉ phi thường là thứ duy trì bạn. Giống như người chiến binh tựa vào chiếc gậy cuối cùng, bạn đã sẵn sàng cho một cú đẩy nữa. Đừng bỏ cuộc bây giờ — chiến thắng chỉ cách bạn một bước chân, và sức mạnh ý chí sẽ đưa bạn qua.', reversedMeaning: 'Sự kiệt sức đang bào mòn cả thể chất lẫn tinh thần, và bạn đang tự hỏi liệu cuộc chiến này có đáng không. Cố chấp bám víu vào con đường cũ dù mọi dấu hiệu đều chỉ ra cần thay đổi chỉ làm tình hình tệ hơn. Hãy biết khi nào cần nghỉ ngơi, nạp lại năng lượng và đánh giá lại liệu mục tiêu ban đầu còn phù hợp với con người bạn hiện tại.' },
  { id: 31, name: 'Mười Gậy', arcana: 'minor', suit: 'wands', keywords: ['gánh nặng', 'trách nhiệm', 'nỗ lực'], uprightMeaning: 'Bạn đang mang trên vai một gánh nặng khổng lồ — quá nhiều trách nhiệm, cam kết và nghĩa vụ đè nặng lên đôi vai. Dù lòng cống hiến của bạn thật đáng ngưỡng mộ, nhưng tiếp tục như thế này sẽ dẫn đến kiệt sức. Mười chiếc gậy quá nặng cho một người — hãy cân nhắc chia sẻ bớt gánh nặng hoặc buông bỏ những cam kết không cần thiết. Bạn không cần phải chứng minh giá trị bằng cách làm tất cả một mình.', reversedMeaning: 'Bạn cuối cùng cũng nhận ra không thể mang tất cả gánh nặng một mình và đang bắt đầu trút bỏ. Hoặc bạn đang trốn tránh trách nhiệm bằng cách đẩy mọi thứ sang người khác. Sự nhẹ nhõm đến khi bạn dám nói "không" với những cam kết quá sức. Hãy tìm điểm cân bằng giữa sự cống hiến và việc chăm sóc bản thân.' },
  { id: 32, name: 'Thị Đồng Gậy', arcana: 'minor', suit: 'wands', keywords: ['nhiệt huyết', 'khám phá', 'tự do'], uprightMeaning: 'Một tia lửa nhiệt huyết trẻ trung đang mang đến những ý tưởng đầy hứng khởi và mới mẻ. Giống như người đưa tin mang theo thông điệp quan trọng, Thị Đồng Gậy báo hiệu tin tức tốt lành về một dự án sáng tạo hoặc cơ hội phiêu lưu. Năng lượng tò mò, phấn khích và sự tự do trong tư duy đang tràn ngập. Hãy khám phá mọi khả năng với đôi mắt rộng mở và trái tim không sợ hãi.', reversedMeaning: 'Năng lượng phân tán và thiếu định hướng đang khiến nhiệt huyết trở nên lãng phí. Bạn có thể nhảy từ ý tưởng này sang ý tưởng khác mà không hoàn thành điều gì. Tin tức bị trì hoãn hoặc thông báo gây thất vọng có thể làm giảm tinh thần. Hãy tập trung năng lượng phân tán thành hành động có ý nghĩa và cam kết với một hướng đi cụ thể.' },
  { id: 33, name: 'Hiệp Sĩ Gậy', arcana: 'minor', suit: 'wands', keywords: ['năng lượng', 'đam mê', 'phiêu lưu'], uprightMeaning: 'Hiệp Sĩ Gậy xông pha trên lưng ngựa chiến với đam mê cháy bỏng và quyết tâm sắt đá. Năng lượng táo bạo, phiêu lưu và dũng cảm đang thúc đẩy bạn hành động ngay lập tức. Đây là thời điểm để theo đuổi ước mơ với tất cả sức lực, bất chấp rủi ro. Sự tự tin bẩm sinh và sức hút cá nhân giúp bạn thu hút đồng minh và cơ hội trên đường đi.', reversedMeaning: 'Sự bốc đồng và thiếu suy nghĩ đang dẫn bạn vào những tình huống nguy hiểm. Hành động liều lĩnh không có kế hoạch chỉ dẫn đến kiệt sức và thất bại. Hiệp sĩ không dây cương là thảm họa — đam mê cần được hướng dẫn bởi trí tuệ. Hãy kiềm chế ngọn lửa bằng chiến lược trước khi xông pha vào trận chiến tiếp theo.' },
  { id: 34, name: 'Nữ Hoàng Gậy', arcana: 'minor', suit: 'wands', keywords: ['tự tin', 'quyết đoán', 'ấm áp'], uprightMeaning: 'Nữ Hoàng Gậy ngồi trên ngai với sự tự tin toát ra từng tế bào, truyền cảm hứng cho tất cả những ai ở xung quanh. Bạn đang tỏa sáng bằng sức hút tự nhiên, sự quyết đoán trong hành động và lòng ấm áp chân thành. Năng lượng lãnh đạo nữ tính mạnh mẽ giúp bạn vừa quản lý hiệu quả vừa tạo dựng lòng trung thành. Sự sáng tạo, đam mê và khả năng truyền động lực đang ở đỉnh cao.', reversedMeaning: 'Sự bất an đang ẩn giấu sau vẻ ngoài mạnh mẽ và quyết đoán. Bạn có thể đang đòi hỏi quá nhiều từ người khác vì chính bạn cũng đang gắng sức quá mức. Sự ghen tị với thành công của người khác hoặc nhu cầu kiểm soát mọi thứ đang làm suy yếu sức hút tự nhiên. Hãy nhìn nhận lại nguồn gốc sự tự tin và tái kết nối với ngọn lửa nội tâm chân thật.' },
  { id: 35, name: 'Quốc Vương Gậy', arcana: 'minor', suit: 'wands', keywords: ['lãnh đạo', 'tầm nhìn', 'doanh nhân'], uprightMeaning: 'Quốc Vương Gậy là nhà lãnh đạo bẩm sinh với tầm nhìn xa trông rộng và sức hút không thể cưỡng lại. Bạn đang dẫn dắt bằng ngọn lửa đam mê, tinh thần doanh nhân táo bạo và khả năng truyền cảm hứng phi thường. Đây là thời điểm để nghĩ lớn, hành động quyết đoán và thiết lập hướng đi cho cả đội ngũ. Uy tín và quyền lực của bạn đang ở đỉnh cao — hãy sử dụng chúng một cách khôn ngoan.', reversedMeaning: 'Phong cách lãnh đạo chuyên quyền và cái tôi quá lớn đang xa rời bạn khỏi những người xung quanh. Kỳ vọng phi thực tế và sự thiếu kiên nhẫn khiến đội ngũ nản lòng thay vì được truyền cảm hứng. Quyền lực thiếu sự đồng cảm tạo ra bất mãn và nổi loạn. Hãy nhớ rằng nhà lãnh đạo vĩ đại dẫn dắt bằng trái tim, không chỉ bằng mệnh lệnh.' },
];

const cups = [
  { id: 36, name: 'Át Cốc', arcana: 'minor', suit: 'cups', keywords: ['tình yêu mới', 'thức tỉnh cảm xúc', 'từ bi'], uprightMeaning: 'Chiếc cốc tràn đầy cảm xúc mang đến một khởi đầu cảm xúc mới — tình yêu, tình bạn sâu sắc, hoặc sự kết nối tâm linh chưa từng có. Một mối quan hệ mới có thể xuất hiện, hoặc mối quan hệ hiện tại được tiếp thêm sinh lực mới. Trực giác và lòng từ bi đang mở rộng, cho phép bạn nhìn thấy vẻ đẹp trong mọi thứ. Hãy mở rộng trái tim và đón nhận dòng chảy cảm xúc tích cực đang tràn vào cuộc đời bạn.', reversedMeaning: 'Sự trống rỗng cảm xúc đang âm thầm bao phủ tâm hồn bạn. Bạn có thể đang kìm nén những cảm xúc cần được giải phóng, hoặc từ chối mở lòng vì sợ bị tổn thương. Chiếc cốc bị lật úp không thể đón nhận tình yêu — hãy tự hỏi điều gì đang ngăn cản bạn cảm nhận sâu sắc. Đôi khi, sự chữa lành bắt đầu bằng việc thừa nhận nỗi đau.' },
  { id: 37, name: 'Hai Cốc', arcana: 'minor', suit: 'cups', keywords: ['đối tác', 'kết hợp', 'hấp dẫn lẫn nhau'], uprightMeaning: 'Một mối quan hệ đẹp đẽ đang hình thành dựa trên sự tôn trọng lẫn nhau, sự hấp dẫn tự nhiên và giá trị chung. Hai tâm hồn gặp gỡ trong sự hòa hợp và cân bằng hoàn hảo — mỗi người bổ khuyết cho nhau. Đây có thể là khởi đầu của tình yêu lãng mạn, tình bạn tri kỷ, hoặc mối quan hệ hợp tác kinh doanh bền chặt. Hãy nuôi dưỡng kết nối này bằng sự chân thành và giao tiếp cởi mở.', reversedMeaning: 'Mối quan hệ đang mất cân bằng — một bên cho đi quá nhiều trong khi bên kia chỉ nhận. Lòng tin có thể đã bị phá vỡ bởi sự hiểu lầm hoặc thiếu giao tiếp chân thành. Giá trị lệch lạc giữa hai người tạo ra căng thẳng ngầm khó giải quyết. Hãy ngồi lại thẳng thắn trao đổi để tìm lại sự hòa hợp, hoặc can đảm thừa nhận rằng mối quan hệ cần được xem xét lại.' },
  { id: 38, name: 'Ba Cốc', arcana: 'minor', suit: 'cups', keywords: ['ăn mừng', 'tình bạn', 'cộng đồng'], uprightMeaning: 'Đây là thời điểm tụ họp bạn bè, ăn mừng và tận hưởng niềm vui cộng đồng. Ba chiếc cốc nâng lên tượng trưng cho sự hợp tác sáng tạo, tình bạn bền chặt và những kỷ niệm đẹp được chia sẻ. Năng lượng tích cực từ những người xung quanh đang nâng cao tinh thần và truyền cảm hứng cho bạn. Hãy trân trọng những mối quan hệ đang có và tạo thêm nhiều khoảnh khắc đáng nhớ.', reversedMeaning: 'Sự cô lập xã hội đang khiến bạn cảm thấy lạc lõng và cô đơn giữa đám đông. Có thể bạn đang bị loại trừ khỏi một nhóm, hoặc tự mình xa rời bạn bè vì thiếu năng lượng giao tiếp. Tin đồn và sự hiểu lầm có thể đang làm rạn nứt tình bạn lâu năm. Hãy chủ động kết nối lại và chọn lọc vòng tròn bạn bè để bao quanh mình bằng những năng lượng tích cực.' },
  { id: 39, name: 'Bốn Cốc', arcana: 'minor', suit: 'cups', keywords: ['thờ ơ', 'suy tư', 'không hài lòng'], uprightMeaning: 'Bạn đang rút lui vào thế giới nội tâm, suy tư và cảm thấy không hài lòng với những gì đang có. Giống như người ngồi dưới bóng cây phớt lờ ba chiếc cốc được trao, bạn có thể đang bỏ lỡ cơ hội ngay trước mắt vì chìm đắm trong suy nghĩ. Sự thờ ơ này có thể là giai đoạn cần thiết để đánh giá lại mong muốn thực sự, nhưng đừng để nó kéo dài quá lâu. Hãy ngẩng đầu lên và nhìn xung quanh — có những món quà cảm xúc đang chờ bạn đón nhận.', reversedMeaning: 'Bạn đang thức tỉnh từ giai đoạn trì trệ cảm xúc và sẵn sàng tái tham gia cuộc sống với động lực mới. Sự rõ ràng về những gì mình thực sự muốn đang dần quay trở lại. Những cơ hội mới bắt đầu thu hút sự chú ý của bạn, và bạn cảm thấy sẵn sàng mở lòng đón nhận. Đây là thời điểm hành động thay vì tiếp tục suy tư.' },
  { id: 40, name: 'Năm Cốc', arcana: 'minor', suit: 'cups', keywords: ['mất mát', 'đau buồn', 'hối tiếc'], uprightMeaning: 'Nỗi đau về những gì đã mất đang che phủ tầm nhìn, khiến bạn không nhận ra những gì vẫn còn bên mình. Ba chiếc cốc đổ tượng trưng cho mất mát, nhưng hai chiếc cốc đứng vững phía sau nhắc nhở bạn rằng không phải tất cả đều đã mất. Hãy cho phép bản thân thương tiếc — đó là quá trình tự nhiên và cần thiết. Nhưng cũng đừng quên quay lại và nhận ra những phước lành vẫn đang chờ đợi.', reversedMeaning: 'Quá trình chữa lành đang dần diễn ra và bạn bắt đầu chấp nhận những mất mát trong quá khứ. Sự hối tiếc đang nhường chỗ cho lòng biết ơn về những bài học đã nhận được. Bạn sẵn sàng tiến lên, buông bỏ nỗi đau cũ và ôm lấy tương lai với trái tim mở rộng hơn. Sự mạnh mẽ thực sự đến từ khả năng đứng dậy sau khi ngã.' },
  { id: 41, name: 'Sáu Cốc', arcana: 'minor', suit: 'cups', keywords: ['hoài niệm', 'hồn nhiên', 'ký ức tuổi thơ'], uprightMeaning: 'Những ký ức ngọt ngào từ quá khứ đang trỗi dậy, mang đến niềm vui hồn nhiên và sự ấm áp của tuổi thơ. Bạn có thể gặp lại người cũ, quay về nơi từng sống, hoặc đơn giản là nhớ lại những khoảnh khắc đẹp đẽ. Đây là thời điểm để kết nối lại với đứa trẻ bên trong và trân trọng những gốc rễ đã tạo nên con người bạn. Hãy để sự hoài niệm nuôi dưỡng tâm hồn nhưng đừng quên sống trong hiện tại.', reversedMeaning: 'Bạn đang sống quá nhiều trong quá khứ, để hoài niệm trở thành xiềng xích ngăn cản sự trưởng thành. Sự lý tưởng hóa những ngày xưa khiến hiện tại luôn thất vọng so với ký ức được tô hồng. Từ chối trưởng thành và đối mặt với thực tế là dấu hiệu cần xem xét. Hãy trân trọng quá khứ nhưng đừng để nó định nghĩa tương lai của bạn.' },
  { id: 42, name: 'Bảy Cốc', arcana: 'minor', suit: 'cups', keywords: ['ảo tưởng', 'lựa chọn', 'mơ mộng'], uprightMeaning: 'Bảy chiếc cốc hiện ra trong làn sương mù, mỗi chiếc chứa đựng một giấc mơ khác nhau — từ tài sản, quyền lực đến tình yêu và sự hiểu biết. Nhưng không phải tất cả đều thực. Bạn đang đứng trước nhiều lựa chọn hấp dẫn nhưng cần phân biệt ảo tưởng với thực tế. Hãy tỉnh táo, đánh giá kỹ mỗi cơ hội và cam kết theo đuổi con đường có ý nghĩa nhất thay vì mơ mộng viển vông.', reversedMeaning: 'Sự rõ ràng cuối cùng đã xuyên qua màn sương ảo tưởng, và bạn bắt đầu nhìn thấy sự thật. Những giấc mơ hão huyền đang nhường chỗ cho sự thực tế lành mạnh. Bạn sẵn sàng đưa ra lựa chọn dựa trên thực tế thay vì viễn cảnh tưởng tượng. Đây là bước trưởng thành quan trọng — hãy cam kết với một con đường cụ thể và hành động.' },
  { id: 43, name: 'Tám Cốc', arcana: 'minor', suit: 'cups', keywords: ['rời bỏ', 'tìm kiếm sự thật', 'vỡ mộng'], uprightMeaning: 'Bạn đang can đảm rời bỏ những gì không còn mang lại ý nghĩa, dù chúng từng rất quan trọng. Tám chiếc cốc xếp gọn gàng phía sau đại diện cho những thành tựu cũ mà bạn chọn bước qua. Cuộc tìm kiếm ý nghĩa sâu xa hơn đòi hỏi sự dũng cảm — nhưng mang lại sự trưởng thành không gì thay thế được. Hãy tin rằng điều bạn đang tìm kiếm xứng đáng với sự hy sinh này.', reversedMeaning: 'Nỗi sợ rời bỏ sự quen thuộc đang giữ chân bạn trong tình trạng không hạnh phúc. Bạn biết cần phải đi nhưng chưa đủ can đảm bước ra. Hoặc bạn đã rời đi nhưng lại lang thang vô mục đích, chưa tìm được điều mình thực sự tìm kiếm. Hãy quyết định dứt khoát: cam kết hoàn toàn với hiện tại hoặc can đảm bước đi không ngoái lại.' },
  { id: 44, name: 'Chín Cốc', arcana: 'minor', suit: 'cups', keywords: ['ước mơ thành hiện thực', 'mãn nguyện', 'hài lòng'], uprightMeaning: 'Đây là lá bài của ước mơ thành hiện thực — sự mãn nguyện, hài lòng và hạnh phúc đang tràn đầy trong cuộc sống. Chín chiếc cốc xếp hàng tượng trưng cho sự dồi dào về cảm xúc, vật chất và tinh thần. Bạn đang ở giai đoạn tận hưởng thành quả xứng đáng sau nhiều nỗ lực. Hãy mỉm cười, tri ân và biết rằng bạn xứng đáng được hạnh phúc này.', reversedMeaning: 'Dù bề ngoài có vẻ đầy đủ, bên trong bạn vẫn cảm thấy thiếu thốn và chưa thỏa mãn. Hạnh phúc hời hợt dựa trên tiện nghi vật chất thiếu chiều sâu cảm xúc thực sự. Ước mơ chưa thành hoàn toàn hoặc kỳ vọng quá cao khiến thực tế luôn thất vọng. Hãy định nghĩa lại hạnh phúc từ bên trong thay vì tìm kiếm nó ở những thứ bên ngoài.' },
  { id: 45, name: 'Mười Cốc', arcana: 'minor', suit: 'cups', keywords: ['hòa thuận', 'gia đình', 'viên mãn cảm xúc'], uprightMeaning: 'Đây là lá bài của sự viên mãn cảm xúc tối thượng — gia đình yêu thương, hòa hợp sâu sắc và hạnh phúc lâu dài. Mười chiếc cốc tạo thành cầu vồng tượng trưng cho sự trọn vẹn trong các mối quan hệ. Trái tim bạn thực sự "về nhà" — được bao quanh bởi tình yêu, sự an toàn và cảm giác thuộc về. Đây là khoảnh khắc để ăn mừng và trân trọng những người đã làm cuộc đời bạn trở nên ý nghĩa.', reversedMeaning: 'Sự bất hòa trong gia đình hoặc mối quan hệ thân thiết đang phá vỡ giấc mơ hạnh phúc viên mãn. Kỳ vọng quá cao về "gia đình hoàn hảo" tạo ra thất vọng khi thực tế không đáp ứng. Có thể có xung đột thế hệ, hiểu lầm giữa các thành viên, hoặc cảm giác lạc lõng ngay trong ngôi nhà của mình. Hãy nỗ lực sửa chữa, giao tiếp chân thành và định nghĩa lại hạnh phúc theo cách riêng của bạn.' },
  { id: 46, name: 'Thị Đồng Cốc', arcana: 'minor', suit: 'cups', keywords: ['cơ hội sáng tạo', 'thông điệp trực giác', 'tò mò'], uprightMeaning: 'Một thông điệp thú vị hoặc cảm hứng sáng tạo bất ngờ đang xuất hiện trong cuộc sống của bạn. Thị Đồng Cốc mang theo tin tức về tình yêu, cơ hội nghệ thuật hoặc sự thức tỉnh trực giác. Hãy đón nhận với sự ngạc nhiên trẻ thơ và trái tim mở rộng. Năng lượng tò mò và nhạy cảm đang giúp bạn nhìn thấy vẻ đẹp ẩn giấu trong những điều bình thường.', reversedMeaning: 'Bế tắc sáng tạo hoặc sự chưa chín chắn cảm xúc đang cản trở sự phát triển. Bạn có thể đang phản ứng quá mức với những tình huống nhỏ, hoặc để cảm xúc chi phối lý trí một cách không lành mạnh. Tin nhắn quan trọng có thể bị bỏ lỡ hoặc hiểu sai. Hãy rèn luyện sự trưởng thành cảm xúc và lắng nghe tiếng nói nội tâm thay vì phản ứng bốc đồng.' },
  { id: 47, name: 'Hiệp Sĩ Cốc', arcana: 'minor', suit: 'cups', keywords: ['lãng mạn', 'quyến rũ', 'trí tưởng tượng'], uprightMeaning: 'Hiệp Sĩ Cốc phi ngựa đến mang theo năng lượng lãng mạn, quyến rũ và trí tưởng tượng phong phú. Đây là thời điểm để theo đuổi tình yêu, sáng tạo nghệ thuật hoặc bất kỳ dự án nào đòi hỏi sự nhạy cảm và trực giác. Sự duyên dáng tự nhiên và khả năng đồng cảm giúp bạn kết nối sâu sắc với người khác. Hãy để trái tim dẫn đường, nhưng đừng quên đặt chân trên mặt đất.', reversedMeaning: 'Kỳ vọng phi thực tế về tình yêu hoặc sự sáng tạo đang dẫn đến thất vọng liên tiếp. Hiệp Sĩ Cốc ngược báo hiệu sự thất thường trong cảm xúc, hứa hẹn suông hoặc ảo tưởng lãng mạn không có cơ sở thực tế. Bạn hoặc ai đó trong cuộc sống đang che đậy sự trống rỗng bằng vẻ ngoài quyến rũ. Hãy nối đất giấc mơ và đánh giá con người thật thay vì hình ảnh lý tưởng.' },
  { id: 48, name: 'Nữ Hoàng Cốc', arcana: 'minor', suit: 'cups', keywords: ['từ bi', 'nuôi dưỡng', 'trực giác'], uprightMeaning: 'Nữ Hoàng Cốc hiện thân cho lòng từ bi sâu sắc, trí tuệ trực giác và năng lực nuôi dưỡng tuyệt vời. Bạn đang dẫn dắt bằng trái tim, đồng cảm với nỗi đau của người khác và tạo ra không gian an toàn cho mọi người. Trực giác cực kỳ mạnh mẽ trong giai đoạn này — hãy tin vào những cảm nhận mà logic không giải thích được. Sự hiện diện của bạn mang lại sự chữa lành và bình an cho xung quanh.', reversedMeaning: 'Sự phụ thuộc cảm xúc hoặc hy sinh bản thân quá mức đang bào mòn năng lượng của bạn. Bạn cho đi nhiều đến mức chiếc cốc của mình đã cạn khô — nhưng vẫn tiếp tục rót. Ranh giới cảm xúc không rõ ràng khiến bạn hấp thu năng lượng tiêu cực từ người khác. Hãy đặt ranh giới lành mạnh và nhớ rằng bạn không thể chăm sóc ai khi chính mình đang kiệt sức.' },
  { id: 49, name: 'Quốc Vương Cốc', arcana: 'minor', suit: 'cups', keywords: ['cân bằng cảm xúc', 'rộng lượng', 'ngoại giao'], uprightMeaning: 'Quốc Vương Cốc là bậc thầy về cảm xúc — dẫn dắt bằng lòng từ bi, trí tuệ cảm xúc và sự cân bằng nội tâm đáng ngưỡng mộ. Bạn đang xử lý các tình huống phức tạp bằng sự bình tĩnh, rộng lượng và tài ngoại giao khéo léo. Khả năng kiểm soát cảm xúc không có nghĩa là kìm nén — mà là hiểu và sử dụng chúng một cách khôn ngoan. Sự hiện diện của bạn mang lại hòa hợp và ổn định cho mọi mối quan hệ.', reversedMeaning: 'Sự thao túng cảm xúc tinh vi hoặc biến động nội tâm ẩn dưới vẻ ngoài bình tĩnh và kiểm soát. Bạn có thể đang sử dụng sự đồng cảm như công cụ để chi phối người khác, hoặc đang kìm nén cảm xúc mãnh liệt cho đến khi chúng bùng nổ. Đôi khi sự "cân bằng" chỉ là mặt nạ che giấu sự hỗn loạn bên trong. Hãy giải quyết cảm xúc chân thật thay vì đóng vai người hoàn hảo.' },
];

const swords = [
  { id: 50, name: 'Át Kiếm', arcana: 'minor', suit: 'swords', keywords: ['minh mẫn', 'đột phá', 'sự thật'], uprightMeaning: 'Một đột phá trí tuệ mạnh mẽ đang xuyên qua màn sương của sự bối rối và do dự. Đây là khoảnh khắc của sự rõ ràng cực độ, nơi sự thật được phơi bày và những ý tưởng mới sắc bén như lưỡi kiếm được hình thành. Hãy sử dụng sức mạnh lý trí này để đưa ra những quyết định dứt khoát và cắt bỏ những gì không còn cần thiết. Một khởi đầu mới dựa trên công lý và logic đang chờ đón bạn.', reversedMeaning: 'Phán đoán của bạn đang bị mờ mịt bởi sự thiếu thông tin hoặc những định kiến cá nhân. Có thể bạn đang sử dụng trí tuệ của mình một cách quá khắc nghiệt hoặc áp đặt, gây ra những hiểu lầm không đáng có. Sự bối rối về mặt trí tuệ có thể dẫn đến những quyết định sai lầm — hãy dừng lại và tìm kiếm thêm sự thật trước khi hành động. Đừng để cái tôi lấn át lý trí trong giai đoạn nhạy cảm này.' },
  { id: 51, name: 'Hai Kiếm', arcana: 'minor', suit: 'swords', keywords: ['quyết định khó', 'bế tắc', 'né tránh'], uprightMeaning: 'Bạn đang đứng trước một lựa chọn khó khăn mà cả hai phương án đều có vẻ ngang bằng nhau về lý lẽ. Sự bế tắc này đòi hỏi bạn phải cân bằng giữa cảm xúc và lý trí, thường là bằng cách bịt mắt để nhìn thấu sự thật nội tâm. Đừng để nỗi sợ đưa ra quyết định sai lầm làm bạn tê liệt — đôi khi việc chọn một hướng đi còn tốt hơn là đứng im mãi mãi. Hãy tìm kiếm sự bình yên trong tâm trí để nghe thấy tiếng nói của sự thật.', reversedMeaning: 'Sự bế tắc cuối cùng đã được phá vỡ khi những thông tin mới hoặc sự thật bất ngờ xuất hiện. Bạn không còn có thể né tránh thực tế và buộc phải đối mặt với quyết định mà bạn đã trì hoãn bấy lâu. Dù sự thật có thể gây khó chịu, nhưng nó mang lại sự giải thoát cần thiết để bạn tiến lên. Hãy cẩn thận với sự quá tải thông tin — hãy tập trung vào cốt lõi của vấn đề thay vì những chi tiết rườm rà.' },
  { id: 52, name: 'Ba Kiếm', arcana: 'minor', suit: 'swords', keywords: ['đau lòng', 'nỗi buồn', 'sự thật đau đớn'], uprightMeaning: 'Một sự thật đau lòng hoặc một mất mát tình cảm đang xuyên thấu tâm hồn bạn, mang đến nỗi buồn sâu sắc. Dù đau đớn, đây là quá trình cần thiết để gột rửa những ảo tưởng và đối diện với thực tế phũ phàng. Hãy cho phép bản thân được đau buồn và khóc thương, vì đây là bước đầu tiên của sự chữa lành. Hãy nhớ rằng sau cơn mưa trời lại sáng, và nỗi đau hiện tại sẽ rèn luyện cho bạn một trái tim kiên cường hơn.', reversedMeaning: 'Quá trình phục hồi từ một nỗi đau lòng hoặc sự phản bội đang dần diễn ra. Bạn bắt đầu buông bỏ những oán hận cũ và chấp nhận thực tế để tâm hồn được nhẹ nhàng hơn. Nỗi buồn đang vơi dần, nhường chỗ cho sự tha thứ và lòng tự trọng. Đây là thời gian để chăm sóc bản thân và tìm kiếm sự hỗ trợ từ những người thân yêu để hoàn tất quá trình chữa lành.' },
  { id: 53, name: 'Bốn Kiếm', arcana: 'minor', suit: 'swords', keywords: ['nghỉ ngơi', 'phục hồi', 'suy tư'], uprightMeaning: 'Sau một giai đoạn căng thẳng, đây là lúc để rút lui, nghỉ ngơi và hồi phục năng lượng. Việc tạm dừng này không phải là dấu hiệu của sự lười biếng hay trốn tránh, mà là sự chuẩn bị cần thiết cho những thử thách tiếp theo. Hãy tìm kiếm sự yên tĩnh, thiền định hoặc đơn giản là dành thời gian một mình để tâm trí được thư giãn hoàn toàn. Sự suy tư sâu sắc trong giai đoạn này sẽ mang lại cho bạn những hiểu biết quý giá.', reversedMeaning: 'Sự bồn chồn hoặc kiệt sức đang bủa vây vì bạn từ chối cho phép bản thân được nghỉ ngơi. Bạn có thể đang cố sức quá mức trong khi cơ thể và tâm trí đã phát đi những tín hiệu quá tải nghiêm trọng. Việc ép buộc bản thân hành động trong trạng thái này chỉ dẫn đến sai lầm và sự suy sụp lâu dài. Hãy lắng nghe cơ thể mình trước khi quá muộn.' },
  { id: 54, name: 'Năm Kiếm', arcana: 'minor', suit: 'swords', keywords: ['xung đột', 'thất bại', 'chiến thắng cay đắng'], uprightMeaning: 'Một cuộc xung đột đã xảy ra và bạn có thể đã giành được phần thắng, nhưng với một cái giá quá đắt. Sự chiến thắng này mang lại vị cay đắng hơn là niềm vui, vì những mối quan hệ có thể đã bị tổn hại nghiêm trọng. Hãy xem xét liệu bạn có đang thắng trong một cuộc tranh cãi nhưng lại thua trong một mối quan hệ hay không. Đôi khi việc hạ cái tôi xuống và tìm kiếm sự thỏa hiệp lại là hành động sáng suốt nhất.', reversedMeaning: 'Mong muốn hòa giải và giải quyết xung đột đang dần trỗi dậy sau một giai đoạn căng thẳng mệt mỏi. Bạn nhận ra rằng việc bám víu vào những oán trách cũ chỉ làm tiêu hao năng lượng mà không mang lại kết quả gì. Sự hối tiếc về những lời nói hoặc hành động trong lúc nóng nảy đang thúc đẩy bạn tìm cách sửa chữa lỗi lầm. Đây là cơ hội để xây dựng lại niềm tin từ đống đổ nát của sự hiểu lầm.' },
  { id: 55, name: 'Sáu Kiếm', arcana: 'minor', suit: 'swords', keywords: ['chuyển tiếp', 'buông bỏ', 'vùng nước lặng'], uprightMeaning: 'Bạn đang thực hiện một cuộc hành trình chuyển tiếp, rời bỏ những bão tố của quá khứ để hướng tới một tương lai bình lặng hơn. Dù việc buông bỏ và ra đi có thể mang theo chút u buồn, nhưng đó là sự thay đổi cần thiết để bạn tìm lại sự an nhiên. Những hỗ trợ thầm lặng từ người khác sẽ giúp bạn vượt qua giai đoạn này một cách suôn sẻ. Hãy tin rằng vùng nước lặng phía trước sẽ mang lại cho bạn sự hồi sinh và hy vọng mới.', reversedMeaning: 'Sự kháng cự đối với việc tiến lên hoặc những "hành lý" cảm xúc chưa được giải quyết đang cản trở hành trình của bạn. Bạn có thể đang cố gắng rời đi nhưng tâm trí vẫn còn vướng bận những vấn đề cũ, khiến con thuyền cuộc đời trở nên nặng nề. Sự trì hoãn việc thay đổi chỉ làm kéo dài cảm giác bất an và mệt mỏi. Hãy dũng cảm đối diện với những gì cần kết thúc để thực sự được tự do bắt đầu chương mới.' },
  { id: 56, name: 'Bảy Kiếm', arcana: 'minor', suit: 'swords', keywords: ['lừa dối', 'chiến lược', 'bí mật'], uprightMeaning: 'Bạn có thể đang cần đến một chiến lược khôn ngoan hoặc những giải pháp sáng tạo để giải quyết một tình huống phức tạp. Tuy nhiên, lá bài này cũng là một lời cảnh báo về sự lừa dối, gian lận hoặc việc trốn tránh trách nhiệm. Hãy cẩn thận với những hành động lén lút của bản thân hoặc của người khác xung quanh bạn. Tính chính trực là điều quan trọng nhất — đừng vì cái lợi trước mắt mà đánh đổi uy tín lâu dài của mình.', reversedMeaning: 'Những bí mật bị che giấu bấy lâu đang bắt đầu được phơi bày ra ánh sáng, hoặc bạn đang cảm thấy nỗ lực gian lận của mình không mang lại kết quả. Sự thú nhận và đối diện với sự thật có thể gây ra khó khăn ban đầu nhưng sẽ mang lại sự nhẹ nhõm cho tâm hồn. Những chiến lược lỏng lẻo đang sụp đổ, yêu cầu bạn phải xây dựng lại dựa trên nền tảng của sự thật. Hãy trung thực với bản thân và người khác để bắt đầu lại.' },
  { id: 57, name: 'Tám Kiếm', arcana: 'minor', suit: 'swords', keywords: ['hạn chế', 'tự giam', 'bế tắc'], uprightMeaning: 'Bạn đang cảm thấy bị vây hãm bởi những rào cản và hạn chế mà dường như không có lối thoát. Tuy nhiên, hãy nhìn kỹ — những xiềng xích và bức tường này phần lớn do chính nỗi sợ hãi và những niềm tin giới hạn của bạn tạo nên. Bạn vẫn có khả năng tự giải thoát mình nếu dám mở mắt nhìn thẳng vào thực tế và bước ra khỏi vùng an toàn tiêu cực. Đừng đợi ai đó đến cứu, chính bạn là người nắm giữ chìa khóa của sự tự do.', reversedMeaning: 'Bạn đang bắt đầu phá vỡ những niềm tin giới hạn và tìm ra cách để bước ra khỏi "nhà tù" tinh thần mà mình đã tự tạo. Sự rõ ràng về những gì thực sự ngăn cản bạn đang xuất hiện, mang lại can đảm để thay đổi tình thế. Bạn nhận ra mình có nhiều quyền lực và sự lựa chọn hơn mình tưởng bấy lâu. Đây là khoảnh khắc của sự thức tỉnh — hãy dũng cảm cởi bỏ dây trói và bước đi.' },
  { id: 58, name: 'Chín Kiếm', arcana: 'minor', suit: 'swords', keywords: ['lo âu', 'ác mộng', 'bất an'], uprightMeaning: 'Nỗi lo âu cực độ, sự hối tiếc hoặc những suy nghĩ đen tối đang làm phiền giấc ngủ và sự bình yên của bạn. Bạn có thể đang tự dằn vặt mình vì những chuyện đã qua hoặc quá lo lắng về một tương lai chưa tới. Hãy nhớ rằng hầu hết những gì chúng ta sợ hãi đều không tồi tệ như cách chúng ta tưởng tượng trong bóng tối. Hãy chia sẻ gánh nặng tinh thần này với ai đó để thấy rằng bạn không hề đơn độc trong cơn ác mộng này.', reversedMeaning: 'Giai đoạn lo âu đen tối nhất đang dần qua đi và bạn bắt đầu tìm thấy những cách lành mạnh để đối phó với nỗi sợ. Ánh sáng của thực tế đang xua tan những ảo ảnh đáng sợ của tiềm thức. Bạn nhận ra rằng việc lo lắng thái quá không giúp ích gì và bắt đầu tập trung vào những hành động thực tế để cải thiện tình hình. Sự hy vọng đang nhen nhóm trở lại — hãy tiếp tục tiến bước ra khỏi bóng tối.' },
  { id: 59, name: 'Mười Kiếm', arcana: 'minor', suit: 'swords', keywords: ['kết thúc', 'đáy vực', 'bình minh mới'], uprightMeaning: 'Bạn cảm thấy như đã chạm đáy vực của sự thất bại, sự phản bội hoặc một kết thúc đau đớn không thể tránh khỏi. Dù tình huống có thể rất tàn khốc, nhưng hãy nhớ rằng khi đã ở dưới đáy, con đường duy nhất còn lại là đi lên. Sự đau đớn này đánh dấu sự kết thúc của một chu kỳ cũ, dọn sạch mọi thứ để một bình minh mới được bắt đầu. Hãy chấp nhận sự thực tại này và chuẩn bị cho một sự khởi sắc đang dần lộ diện ở phía chân trời.', reversedMeaning: 'Quá trình phục hồi từ một sự sụp đổ hoặc tàn phá nặng nề đang bắt đầu diễn ra một cách chậm rãi nhưng chắc chắn. Bạn đang thu thập những mảnh vỡ của cuộc đời mình để xây dựng lại một thứ gì đó mới mẻ và vững chắc hơn. Dù vết sẹo vẫn còn đó, nhưng sức mạnh sinh tồn đang giúp bạn đứng dậy và bước tiếp. Hãy tin rằng thời kỳ đen tối nhất đã thực sự ở đằng sau lưng bạn.' },
  { id: 60, name: 'Thị Đồng Kiếm', arcana: 'minor', suit: 'swords', keywords: ['tò mò', 'nhanh nhạy', 'cảnh giác'], uprightMeaning: 'Một tâm trí sắc bén, tò mò và đầy năng lượng đang sẵn sàng khám phá những ý tưởng mới hoặc những thông tin thú vị. Thị Đồng Kiếm mang theo tinh thần cảnh giác và khả năng giao tiếp nhanh nhạy, giúp bạn nắm bắt những thay đổi xung quanh một cách dễ dàng. Hãy sử dụng trí tuệ trẻ trung này để học hỏi và giải quyết các vấn đề bằng tư duy logic. Một cơ hội mới liên quan đến trí tuệ hoặc tin tức bất ngờ có thể xuất hiện.', reversedMeaning: 'Bạn có thể đang đưa ra những lời phán xét vội vàng hoặc giao tiếp một cách thiếu thốn sự chín chắn. Những ý tưởng hời hợt hoặc việc "nói mà không làm" có thể gây ra những hiểu lầm hoặc rắc rối nhỏ. Sự cảnh giác biến thành nghi ngờ vô căn cứ, hoặc bạn đang sử dụng ngôn từ để gây tổn thương người khác một cách bốc đồng. Hãy chậm lại, lắng nghe nhiều hơn và suy nghĩ kỹ trước khi phát ngôn.' },
  { id: 61, name: 'Hiệp Sĩ Kiếm', arcana: 'minor', suit: 'swords', keywords: ['tham vọng', 'tư duy nhanh', 'quyết đoán'], uprightMeaning: 'Hiệp Sĩ Kiếm xông pha với sự mãnh liệt trí tuệ, tham vọng và mong muốn đạt được kết quả ngay lập tức. Bạn đang sở hữu một tư duy nhanh nhạy và sự quyết đoán đáng kinh ngạc để vượt qua mọi rào cản trên con đường của mình. Tuy nhiên, hãy cẩn thận đừng để tốc độ làm bạn bỏ lỡ những chi tiết quan trọng hoặc dẫm lên cảm xúc của người khác. Sự tập trung và nghị lực sẽ đưa bạn đến đích rất nhanh chóng.', reversedMeaning: 'Sự vội vàng liều lĩnh và thiếu kiểm soát đang khiến bạn hành động một cách thiếu suy nghĩ, dẫn đến những sai lầm không đáng có. Bạn có thể đang "đốt cầu" đằng sau mình hoặc gây ra những xung đột vô nghĩa do sự bốc đồng. Đam mê trí tuệ khi thiếu đi mục đích rõ ràng sẽ trở nên phân tán và tiêu tốn năng lượng một cách vô ích. Hãy kìm nén cơn lốc của mình và xác định lại hướng đi trước khi tiếp tục bứt phá.' },
  { id: 62, name: 'Nữ Hoàng Kiếm', arcana: 'minor', suit: 'swords', keywords: ['giao tiếp rõ ràng', 'độc lập', 'sáng suốt'], uprightMeaning: 'Nữ Hoàng Kiếm hiện thân cho sự sáng suốt, giao tiếp trực diện và khả năng nhìn thấu mọi ảo tưởng bằng trí tuệ sắc sảo. Bạn đang đứng ở vị thế độc lập, sử dụng kinh nghiệm và sự công tâm để đưa ra những nhận định đúng đắn. Sự trung thực và rõ ràng trong ngôn từ giúp bạn tạo ra ranh giới lành mạnh và giải quyết các vấn đề hiệu quả. Hãy tin vào khả năng phán đoán của mình và đừng ngại nói lên sự thật.', reversedMeaning: 'Sự sáng suốt có thể đang biến thành sự lạnh lùng xa cách hoặc những lời chỉ trích quá mức khắc nghiệt. Bạn có thể đang sử dụng trí tuệ của mình như một tấm khiên để ngăn cản sự kết nối cảm xúc, hoặc để thao túng người khác bằng ngôn từ sắc mỏng. Những nỗi đau trong quá khứ có thể đang khiến bạn trở nên cay nghiệt — hãy học cách cân bằng giữa cái đầu lạnh và trái tim ấm áp để không làm tổn thương những người xung quanh.' },
  { id: 63, name: 'Quốc Vương Kiếm', arcana: 'minor', suit: 'swords', keywords: ['quyền lực trí tuệ', 'sự thật', 'lãnh đạo đạo đức'], uprightMeaning: 'Quốc Vương Kiếm là bậc thầy của logic, sự công bằng và lãnh đạo bằng những chuẩn mực đạo đức cao nhất. Bạn đang dẫn dắt với sự minh mẫn trí tuệ, khả năng phân tích mọi khía cạnh của vấn đề và đưa ra những lời khuyên thông thái. Sự liêm chính và tình yêu đối với sự thật là sức mạnh lớn nhất của bạn lúc này. Hãy sử dụng quyền lực của mình để thiết lập trật tự và bảo vệ lẽ phải bằng lập luận sắc bén.', reversedMeaning: 'Sự độc đoán, lạm dụng sức mạnh trí tuệ hoặc những lý luận thao túng đang khiến bạn mất đi sự ủng hộ của mọi người. Bạn có thể đang quá cứng nhắc với những quy tắc mà quên đi yếu tố con người, hoặc sử dụng sự thông minh của mình để phục vụ cho những mục đích ích kỷ. Một nhà lãnh đạo trí tuệ nếu thiếu đi sự thấu cảm sẽ trở thành một bạo chúa tinh thần. Hãy xem xét lại cách bạn áp dụng logic và sự thật vào thực tế cuộc sống.' },
];


const pentacles = [
  { id: 64, name: 'Át Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['cơ hội mới', 'thịnh vượng', 'hiện thực hóa'], uprightMeaning: 'Một cơ hội vàng cho sự phát triển tài chính hoặc sự nghiệp đang xuất hiện rạng rỡ trước mắt bạn. Đây là thời điểm lý tưởng để gieo hạt giống cho sự thịnh vượng lâu dài và biến những kế hoạch thực tế thành hiện thực. Hãy nắm bắt lấy món quà vật chất này với lòng biết ơn và sự siêng năng để xây dựng một nền tảng vững chắc cho tương lai. Sự dồi dào đang gõ cửa cuộc đời bạn.', reversedMeaning: 'Cơ hội tài chính có thể bị bỏ lỡ do sự thiếu chuẩn bị hoặc những kế hoạch quản lý kém hiệu quả. Bạn có thể đang quá tập trung vào cái lợi trước mắt mà quên đi tầm nhìn dài hạn, dẫn đến sự lãng phí tài nguyên. Sự bất ổn về mặt vật chất khiến bạn cảm thấy lo lắng và thiếu an toàn — hãy rà soát lại ngân sách và thắt chặt kỷ luật tài chính. Đừng vội vàng đầu tư khi chưa hiểu rõ mọi rủi ro.' },
  { id: 65, name: 'Hai Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['cân bằng', 'thích nghi', 'ưu tiên'], uprightMeaning: 'Bạn đang tung hứng nhiều ưu tiên, trách nhiệm và nguồn lực tài chính với một kỹ năng và sự khéo léo đáng kinh ngạc. Sự thích nghi linh hoạt giúp bạn giữ được thăng bằng giữa những biến động không ngừng của cuộc sống vật chất. Hãy giữ vững tinh thần lạc quan và tập trung vào việc quản lý thời gian hiệu quả để không bị quá tải. Bạn có khả năng xử lý mọi thứ nếu biết cách sắp xếp thứ tự ưu tiên đúng đắn.', reversedMeaning: 'Sự choáng ngợp trước quá nhiều gánh nặng và trách nhiệm đang khiến bạn mất đi sự thăng bằng cần thiết. Việc cố gắng làm quá nhiều việc cùng lúc chỉ dẫn đến sự kiệt sức và những sai sót trong quản lý tài chính. Bạn có thể đang cảm thấy cuộc sống vượt khỏi tầm kiểm soát và tâm trí trở nên rối bời. Hãy dừng lại, trút bỏ những việc không cần thiết và tập trung vào những gì thực sự quan trọng lúc này.' },
  { id: 66, name: 'Ba Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['làm việc nhóm', 'tay nghề', 'hợp tác'], uprightMeaning: 'Kỹ năng và tay nghề chuyên môn của bạn đang được công nhận và đánh giá cao trong một dự án tập thể. Sự hợp tác nhịp nhàng giữa các cá nhân có cùng mục tiêu mang lại những kết quả xuất sắc vượt xa mong đợi. Đây là thời điểm tuyệt vời để học hỏi từ người khác và đóng góp tài năng của mình vào một công trình ý nghĩa. Hãy tự hào về sự tiến bộ và chất lượng công việc mà bạn đang cùng đội ngũ tạo ra.', reversedMeaning: 'Thiếu tinh thần đồng đội hoặc sự bất đồng trong cách làm việc đang làm chậm tiến độ và giảm chất lượng công việc. Bạn có thể cảm thấy tài năng của mình bị phớt lờ hoặc đang phải làm việc với những người không cùng chí hướng. Sự thiếu kỷ luật và quy trình làm việc cẩu thả dẫn đến những kết quả đáng thất vọng. Hãy xem xét lại cách giao tiếp và tìm kiếm sự đồng thuận để đưa dự án quay lại đúng quỹ đạo.' },
  { id: 67, name: 'Bốn Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['an toàn', 'bảo tồn', 'kiểm soát'], uprightMeaning: 'Bạn đang đạt được sự an ninh tài chính nhờ vào việc quản lý cẩn thận, tiết kiệm và bảo tồn nguồn lực. Sự ổn định vật chất mang lại cho bạn cảm giác yên tâm và vững chắc trong cuộc sống. Tuy nhiên, hãy cẩn thận đừng để sự bảo thủ quá mức ngăn cản bạn tận hưởng cuộc sống hoặc nắm bắt những cơ hội mới. Hãy thiết lập một ranh giới an toàn nhưng đừng để nó trở thành một bức tường ngăn cách bạn với dòng chảy của sự dồi dào.', reversedMeaning: 'Sự tham lam, quá chú trọng vào vật chất hoặc nỗi sợ mất mát đang khiến tâm trí bạn trở nên cứng nhắc và hẹp hòi. Việc bám víu quá chặt vào những gì mình có ngăn cản sự lưu thông của năng lượng và tiền bạc trong cuộc đời bạn. Sự chi tiêu bốc đồng hoặc quản lý lỏng lẻo có thể dẫn đến những thất thoát không đáng có. hãy học cách buông bỏ bớt sự kiểm soát và tin tưởng hơn vào sự vận hành của vũ trụ.' },
  { id: 68, name: 'Năm Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['khó khăn tài chính', 'thiếu thốn', 'cô lập'], uprightMeaning: 'Bạn có thể đang trải qua một giai đoạn khó khăn về mặt tài chính, sức khỏe hoặc cảm thấy bị cô lập khỏi sự giúp đỡ. Cảm giác thiếu thốn và lo âu đang đè nặng lên tâm trí, khiến bạn chỉ nhìn thấy những gì mình mất đi. Tuy nhiên, hãy nhớ rằng sự giúp đỡ và nguồn lực luôn hiện hữu xung quanh — bạn chỉ cần đủ khiêm nhường để tìm cầu và đón nhận. Đừng để niềm kiêu hãnh ngăn cản bạn bước vào căn phòng ấm áp của sự sẻ chia.', reversedMeaning: 'Quá trình phục hồi từ một giai đoạn mất mát tài chính hoặc bệnh tật đang bắt đầu có những tín hiệu tích cực. Những nguồn lực mới, sự giúp đỡ bất ngờ hoặc một công việc mới đang xuất hiện để giúp bạn đứng dậy. Sự tự tin đang dần quay trở lại khi bạn nhận ra rằng mình có đủ sức mạnh để vượt qua nghịch cảnh. Hãy mở lòng đón nhận những cơ hội mới và trân trọng những bài học xương máu mà giai đoạn khó khăn đã mang lại cho bạn.' },
  { id: 69, name: 'Sáu Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['rộng lượng', 'chia sẻ', 'cho và nhận'], uprightMeaning: 'Sự rộng lượng và lòng từ bi đang tuôn chảy một cách hài hòa trong cuộc đời bạn theo cả hai hướng. Bạn có thể đang ở vị thế của người cho đi tài lực, kiến thức hoặc sự hỗ trợ cho những người cần đến. Hoặc bạn đang nhận được sự giúp đỡ xứng đáng để vượt qua khó khăn hiện tại. Hãy trân trọng sự lưu thông tuyệt vời này và luôn ghi nhớ giá trị của sự sẻ chia công bằng. Hạnh phúc thực sự nằm ở việc biết cách cho và nhận một cách cân bằng.', reversedMeaning: 'Sự hào phóng có thể đang bị lợi dụng hoặc mang theo những điều kiện ngầm khiến mối quan hệ trở nên mất cân bằng. Có một sự chênh lệch quyền lực khó chịu trong việc cho và nhận, dẫn đến cảm giác nợ nần hoặc bị hạ thấp. Bạn có thể đang chi tiêu quá mức cho những người không xứng đáng hoặc từ chối giúp đỡ khi mình hoàn toàn có khả năng. hãy xem xét lại động cơ của sự cho đi và thiết lập sự công bằng thực sự trong mọi giao dịch.' },
  { id: 70, name: 'Bảy Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['kiên nhẫn', 'đầu tư', 'tầm nhìn dài hạn'], uprightMeaning: 'Những khoản đầu tư kiên nhẫn và nỗ lực bền bỉ của bạn đang dần đơm hoa kết trái. Đây là lúc paused lại để đánh giá tiến độ, quan sát sự trưởng thành của thành quả và lên kế hoạch cho vụ thu hoạch tiếp theo. Đừng vội vã hái quả khi còn xanh — sự kiên nhẫn thêm một chút nữa sẽ mang lại kết quả trọn vẹn nhất. Hãy tin vào quá trình tự nhiên và tự hào về những gì mình đã chăm sóc bấy lâu.', reversedMeaning: 'Sự thiếu kiên nhẫn với những kết quả đến chậm đang khiến bạn cảm thấy nản lòng và muốn bỏ cuộc giữa chừng. Bạn có thể đang lo lắng về việc liệu nỗ lực của mình có mang lại lợi nhuận xứng đáng hay không, dẫn đến những quyết định thay đổi vội vàng. Năng lượng phân tán hoặc quản lý không hiệu quả khiến thành quả bị đình trệ. Hãy bình tĩnh lại, kiểm tra lại quy trình và nhớ rằng những cây đại thụ đều cần thời gian dài để trưởng thành.', },
  { id: 71, name: 'Tám Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['kỹ năng', 'tay nghề', 'siêng năng'], uprightMeaning: 'Sự cống hiến hết mình cho nghề nghiệp và việc rèn luyện kỹ năng mỗi ngày đang dần đưa bạn đến sự thành thạo đỉnh cao. Bạn đang tập trung tuyệt đối vào công việc, chăm chút cho từng chi tiết nhỏ với lòng đam mê và sự siêng năng đáng nể. Đây là giai đoạn của sự tích lũy kiến thức và xây dựng uy tín bằng chất lượng thực tế. Thành công bền vững sẽ theo sau những nỗ lực tự thân không ngừng nghỉ của bạn.', reversedMeaning: 'Cảm giác cầu toàn thái quá hoặc sự nhàm chán trong công việc lặp đi lặp lại đang làm giảm hứng thú của bạn. Bạn có thể đang làm việc một cách máy móc mà không có sự sáng tạo, hoặc quá sa đà vào những chi tiết không quan trọng mà bỏ quên bức tranh toàn cảnh. Sự thiếu tập trung hoặc lười biếng tạm thời đang ảnh hưởng đến chất lượng đầu ra. Hãy tìm kiếm sự đổi mới trong cách làm hoặc đặt ra những thử thách mới để thắp lại ngọn lửa đam mê với nghề nghiệp.' },
  { id: 72, name: 'Chín Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['xa hoa', 'tự lập', 'thành tựu'], uprightMeaning: 'Bạn đã xây dựng được một cuộc sống thoải mái, xa hoa và tự lập bằng chính nỗ lực và sự khôn ngoan của bản thân. Đây là lúc để tận hưởng thành quả của sự kỷ luật và lòng tự trọng cao độ. Bạn cảm thấy hòa hợp với thiên nhiên và trân trọng vẻ đẹp sang trọng xung quanh mình. Sự độc lập về tài chính mang lại cho bạn tự do để theo đuổi những giá trị tinh thần cao hơn. Hãy mỉm cười với sự viên mãn mà bạn xứng đáng nhận được.', reversedMeaning: 'Sự phụ thuộc quá mức vào những tiện nghi vật chất hoặc vẻ bề ngoài xa hoa đang khiến bạn mất dần sự kết nối với bản thân. Bạn có thể đang sống vượt quá khả năng tài chính của mình hoặc cảm thấy cô đơn ngay trong sự đầy đủ. Việc thiếu tự lập hoặc sự hời hợt trong các giá trị sống đang tạo ra một cảm giác trống rỗng ngầm. Hãy quay lại với sự đơn giản, rèn luyện lại tính kỷ luật và tìm kiếm niềm vui từ những giá trị nội tại thay vì chỉ dựa vào đồ vật.' },
  { id: 73, name: 'Mười Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['giàu có', 'di sản', 'thịnh vượng gia đình'], uprightMeaning: 'Sự giàu có bền vững, sự thịnh vượng của gia đình và một di sản lâu đời đang là những giá trị nổi bật trong cuộc đời bạn. Những nỗ lực của thế hệ trước và của chính bạn đã tạo nên một nền tảng an ninh vững chắc vượt xa giới hạn của bản thân. Bạn được bao quanh bởi sự ủng hộ của cộng đồng và sự ấm áp của truyền thống. Đây là khoảnh khắc của sự trọn vẹn về vật chất và sự kết nối huyết thống sâu sắc. Hãy trân trọng và bảo tồn di sản quý giá này.', reversedMeaning: 'Những tranh chấp về tài chính trong gia đình hoặc sự lung lay của các giá trị truyền thống đang gây ra sự bất ổn. Bạn có thể cảm thấy gánh nặng của kỳ vọng gia đình quá lớn hoặc đang lo lắng về việc mất đi tài sản thừa kế. Sự giàu có hời hợt không đi kèm với hạnh phúc thực sự trong tổ ấm. Hãy tập trung vào việc hàn gắn các mối quan hệ và xây dựng lại sự ổn định dựa trên sự hiểu biết và tôn trọng lẫn nhau thay vì chỉ dựa vào tiền bạc.' },
  { id: 74, name: 'Thị Đồng Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['tham vọng', 'học hỏi', 'dự án mới'], uprightMeaning: 'Người học trò háo hức trong bạn đang sẵn sàng học hỏi những kiến thức mới và bắt tay vào những dự án thực tế đầy triển vọng. Thị Đồng Tiền mang theo tin tức về một cơ hội nghề nghiệp, một khóa học hoặc một khởi đầu kinh doanh nhỏ nhưng vững chắc. Hãy giữ vững tham vọng lành mạnh và sự siêng năng để biến những ý tưởng trên giấy thành hiện thực. Sự kiên trì và thái độ thực tế sẽ giúp bạn tiến xa trên con đường phát triển bản thân.', reversedMeaning: 'Sự thiếu tập trung, trì hoãn hoặc những ý tưởng thiếu thực tế đang cản trở bước tiến của bạn. Bạn có thể đang mơ mộng về thành công nhanh chóng mà không muốn bỏ ra nỗ lực rèn luyện cần thiết. Những thông tin về tài chính hoặc dự án có thể bị trì hoãn hoặc mang lại sự thất vọng. Hãy rèn luyện lại kỷ luật bản thân, lập kế hoạch chi tiết và bắt đầu từ những việc nhỏ nhất thay vì mơ mộng viễn vông.' },
  { id: 75, name: 'Hiệp Sĩ Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['chăm chỉ', 'kỷ luật', 'trách nhiệm'], uprightMeaning: 'Hiệp Sĩ Tiền tiến lên một cách chậm rãi nhưng chắc chắn bằng nỗ lực đều đặn, sự kỷ luật thép và tinh thần trách nhiệm cao độ. Bạn là người đáng tin cậy nhất trong đội ngũ, luôn hoàn thành nhiệm vụ với sự tận tâm tuyệt đối. Thành công của bạn không đến từ vận may mà từ sự tích lũy bền bỉ qua thời gian. Hãy kiên trì với con đường mình đã chọn, dù có vẻ tẻ nhạt, vì nó chắc chắn sẽ dẫn bạn đến đích một cách an toàn nhất.', reversedMeaning: 'Sự trì trệ, lười biếng hoặc chủ nghĩa cầu toàn ám ảnh đang khiến bạn bị kẹt lại một chỗ. Bạn có thể đang trở nên quá cứng nhắc với những thói quen cũ và sợ hãi sự thay đổi, hoặc đang mệt mỏi với những công việc lặp đi lặp lại vô nghĩa. Sự thiếu linh hoạt khiến bạn bỏ lỡ những cơ hội tốt đang trôi qua. hãy nới lỏng sự kiểm soát, tìm kiếm sự mới mẻ trong công việc và cho phép bản thân được vận động linh hoạt hơn để phá vỡ sự bế tắc hiện tại.' },
  { id: 76, name: 'Nữ Hoàng Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['nuôi dưỡng sung túc', 'chăm sóc thực tế', 'gia đình'], uprightMeaning: 'Nữ Hoàng Tiền hiện thân cho sự nuôi dưỡng dồi dào, khả năng chăm sóc thực tế tuyệt vời và một trái tim ấm áp dành cho gia đình. Bạn đang tạo ra một môi trường an toàn, tiện nghi và đầy đủ cho bản thân và những người thân yêu bằng sự khéo léo và nhạy bén của mình. Sự kết nối với thiên nhiên và những giá trị thực tế giúp bạn giữ được sự bình yên nội tâm. Hãy tiếp tục lan tỏa sự thịnh vượng ấm áp này đến mọi người xung quanh.', reversedMeaning: 'Bạn có thể đang bỏ bê bản thân hoặc gia đình vì mải mê theo đuổi những giá trị vật chất phù hợp với sự thiếu hụt nội tâm. Sự lo âu về tài chính hoặc nhu cầu kiểm soát quá mức không gian sống gây ra căng thẳng cho các mối quan hệ. Đôi khi bạn quên mất việc tận hưởng những gì mình có và chỉ mải miết tích trữ một cách sợ hãi. Hãy khôi phục lại sự cân bằng giữa việc kiếm tiền và việc chăm sóc tâm hồn, tận hưởng sự đơn giản và tình yêu thương chân thành.' },
  { id: 77, name: 'Quốc Vương Tiền', arcana: 'minor', suit: 'pentacles', keywords: ['giàu có', 'nhạy bén kinh doanh', 'lãnh đạo vững vàng'], uprightMeaning: 'Quốc Vương Tiền là bậc thầy của thế giới vật chất, người đã xây dựng được một đế chế thịnh vượng bằng sự kiên nhẫn, trí tuệ và sự nhạy bén kinh doanh xuất chúng. Bạn dẫn dắt với sự vững vàng, tầm nhìn thực tế và khả năng biến mọi nguồn lực thành lợi nhuận bền vững. Đây là thời gian của sự thành đạt đỉnh cao, nơi uy tín và quyền lực của bạn được thiết lập vững chắc. Hãy sử dụng sự giàu có của mình để bảo vệ và phát triển cộng đồng.', reversedMeaning: 'Tham lam, nghiện công việc hoặc những quyết định tài chính liều lĩnh đang đe dọa sự ổn định mà bạn đã dày công xây dựng. Cái tôi quá lớn và sự chú trọng quá mức vào quyền lực vật chất khiến bạn trở nên độc đoán và thiếu sự thấu cảm. Bạn có thể đang đánh giá con người chỉ qua giá trị tài sản mà quên đi những phẩm chất tinh thần quý giá. hãy nhìn lại mục đích thực sự của sự thịnh vượng và khôi phục lại những giá trị đạo đức trong kinh doanh và lãnh đạo.' },
];


export const allCards = [...majorArcana, ...wands, ...cups, ...swords, ...pentacles];

// Xào bài và rút 3 lá ngẫu nhiên
export const drawThreeCards = () => {
  const shuffled = [...allCards].sort(() => Math.random() - 0.5);
  const positions = ['past', 'present', 'future'];
  return shuffled.slice(0, 3).map((card, i) => ({
    card,
    reversed: Math.random() < 0.3, // 30% cơ hội lá ngược
    position: positions[i],
    flipped: false,
  }));
};

// Tổng hợp lời khuyên chung dựa trên 3 lá và chủ đề
export const generateSynthesis = (drawnCards, topic = 'Tổng quan') => {
  const majorCount = drawnCards.filter(d => d.card.arcana === 'major').length;
  const reversedCount = drawnCards.filter(d => d.reversed).length;

  let energy = '';
  if (majorCount >= 2) energy = 'Năng lượng rất mạnh mẽ từ các lá Ẩn Chính đang chi phối vận mệnh của bạn. Đây là giai đoạn bước ngoặt quan trọng.';
  else if (majorCount === 1) energy = 'Sự kết hợp giữa Ẩn Chính và Ẩn Phụ cho thấy một sự kiện quan trọng đang ảnh hưởng đến cuộc sống hàng ngày.';
  else energy = 'Các lá Ẩn Phụ cho thấy những ảnh hưởng thực tế trong cuộc sống hàng ngày đang chiếm ưu thế.';

  let mood = '';
  if (reversedCount === 0) mood = 'Tất cả các lá đều thuận, cho thấy năng lượng tích cực và thuận lợi đang bao quanh bạn.';
  else if (reversedCount === 1) mood = 'Có một lá ngược cho thấy một khía cạnh cần được chú ý và cải thiện trong khi các mặt khác đang thuận lợi.';
  else if (reversedCount === 2) mood = 'Hai lá ngược báo hiệu những thử thách đáng kể cần sự chú ý đặc biệt và nỗ lực vượt qua.';
  else mood = 'Ba lá ngược cho thấy giai đoạn nhiều biến động — nhưng hãy nhớ rằng mỗi thử thách là cơ hội để trưởng thành.';

  let topicAdvice = '';
  if (topic === 'Tình yêu & Mối quan hệ') {
     topicAdvice = 'Về mặt tình cảm, hãy chú ý đến sự gắn kết và giao tiếp chân thành. Đừng để cái tôi hoặc sự hiểu lầm làm rạn nứt mối quan hệ. ';
  } else if (topic === 'Sự nghiệp & Sự nghiệp') {
     topicAdvice = 'Trong công việc và sự nghiệp, hãy duy trì sự kỷ luật và tập trung. Cơ hội đang tồn tại, nhưng cần sự chuyên cần để khai phá. ';
  } else if (topic === 'Sự nghiệp & Tài chính' || topic === 'Tài chính') {
     topicAdvice = 'Về tiền bạc và tài chính, hãy cẩn trọng với các khoản đầu tư và chi tiêu bốc đồng. Duy trì kỷ luật sẽ là chìa khóa dài hạn. ';
  } else if (topic === 'Sức khỏe & Tinh thần') {
     topicAdvice = 'Giai đoạn này, thiền tĩnh lặng và tự chăm sóc bản thân là ưu tiên hàng đầu. Hãy lắng nghe cơ thể và buông bỏ căng thẳng. ';
  } else {
     topicAdvice = 'Hãy giữ một nhãn quan bao quát để nhìn nhận đầy đủ bức tranh cuộc sống. ';
  }

  return {
    energy,
    mood,
    advice: `${topicAdvice}Hãy suy ngẫm về thông điệp của từng lá bài và ứng dụng nó theo chủ đề '${topic}'. Tarot không ấn định tương lai — vị quyết định nằm ở chính bạn.`
  };
};
